### ISSUE TITLE
401 Unauthorized HTTP Response when trying to download all Tracks (-a) on specific account

### ISSUE THREAD

**Issue by FloThinksPi** [flyingrub/scdl#106]
Getting following result , auth token is set and working.
Other Accounds work flawless. Only mrsuicidesheep gets me the 401.

> scdl -l https://soundcloud.com/mrsuicidesheep/tracks

works but does only downlad 1. Page (50 Tracks)

Here is the output on the problem:

```
[flo@fdh Downloads]$ scdl -l https://soundcloud.com/mrsuicidesheep -a 
Soundcloud Downloader

Found an user profile
Retrieving all the track of user MrSuicideSheep...
Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.4.1', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.4/site-packages/scdl/scdl.py", line 114, in main
    parse_url(arguments['-l'])
  File "/usr/lib/python3.4/site-packages/scdl/scdl.py", line 189, in parse_url
    download_all_user_tracks(item)
  File "/usr/lib/python3.4/site-packages/scdl/scdl.py", line 228, in download_all_user_tracks
    response = urllib.request.urlopen(url)
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib64/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

```

Can someone reproduce ?

**Comment by flyingrub** [comment]
confirmed.
I think they blocked my clientID...

**Comment by flyingrub** [comment]
mm...
It seems to be with random account (mine too is blocked...) and not related to the clientID.

**Comment by FloThinksPi** [comment]
curl -v 'http://api.soundcloud.com/resolve.json?url=http://soundcloud.com/mrsuicidesheep&client_id=a3e059563d7fd3372b49b37f00a00bcf'

To get Client id , then

https://api-v2.soundcloud.com/profile/soundcloud:users:3399796?limit=200&offset=0&client_id=a3e059563d7fd3372b49b37f00a00bcf 

Works and gives valid response , dont find whats fishy here. :fish:

**Comment by FloThinksPi** [comment]
@flyingrub 
See PullRequest for Workaround/PotentialFix and cause of the issue ;)

**Comment by flyingrub** [comment]
`scdl -l https://soundcloud.com/mrsuicidesheep/tracks`
>>
`scdl -l https://soundcloud.com/mrsuicidesheep -t`

**Comment by FloThinksPi** [comment]
True but this issue is about 

> scdl -l https://soundcloud.com/mrsuicidesheep -a

the example with /tracks was just to say that it works this way , but not with -a

**Comment by flyingrub** [comment]
i'm working on it.
