### ISSUE TITLE
Error while fetching user favorites and errno104

### ISSUE THREAD

**Issue by xnrx** [flyingrub/scdl#112]
I'm now at latest commit (and was on latest commit before).

Previous bug was not fixed (errno 104). 
```
[music/like] scdl -l https://soundcloud.com/sacredaus/tilendria-falls
Soundcloud Downloader

Found a track
Downloading Tilendria Falls
Downloading the orginal file.
[################################] 29/7502 - 00:00:00
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 660, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.4.1', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 115, in main
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 180, in parse_url
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 383, in download_track
  File "/usr/lib/python3.5/site-packages/clint-0.5.1-py3.5.egg/clint/textui/progress.py", line 115, in bar
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 663, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

And now after f54ab00bff069205ac04183dc35f4f9e8d689b59, i cant download my favorites, scdl respond this:
```
[music/like] scdl -l https://soundcloud.com/rst-x0 -f
Soundcloud Downloader

Found a user profile
Retrieving the favorites of user Rst x0...
Retrieved 118 favorites
Favorite n°1 of 118
'Resource' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 265, in download_all_of_user
    download_function(item)
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 341, in download_track
    if track['streamable']:
TypeError: 'Resource' object is not subscriptable
Favorite n°2 of 118
'Resource' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 265, in download_all_of_user
    download_function(item)
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 341, in download_track
    if track['streamable']:
TypeError: 'Resource' object is not subscriptable
Favorite n°3 of 118
'Resource' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 265, in download_all_of_user
    download_function(item)
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 341, in download_track
    if track['streamable']:
TypeError: 'Resource' object is not subscriptable
Favorite n°4 of 118
'Resource' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 265, in download_all_of_user
    download_function(item)
  File "/usr/lib/python3.5/site-packages/scdl-1.4.1-py3.5.egg/scdl/scdl.py", line 341, in download_track
    if track['streamable']:
TypeError: 'Resource' object is not subscriptable
```

**Comment by flyingrub** [comment]
```
0 fly@Minotoor ~/Musique/test $ scdl -l https://soundcloud.com/sacredaus/tilendria-falls
Soundcloud Downloader

Found a track
Downloading Tilendria Falls
Downloading the orginal file.
[################################] 7502/7502 - 00:00:01

Settings tags...

"Tilendria Falls 3.mp3" Downloaded.

0 fly@Minotoor ~/Musique/test $ scdl -l https://soundcloud.com/rst-x0 -f
Soundcloud Downloader

Found a user profile
Retrieving the favorites of user Rst x0...
Retrieved 118 favorites
Favorite n°1 of 118
Downloading Clouds Cross Skies
[################################] 2347/2347 - 00:00:02

Settings tags...

Clouds Cross Skies.mp3 Downloaded.

Favorite n°2 of 118
Downloading Kasger - Wait For Me
[################################] 4054/4054 - 00:00:00

Settings tags...

Kasger - Wait For Me.mp3 Downloaded.

Favorite n°3 of 118
Downloading Tilendria Falls
Downloading the orginal file.

Music already exists ! (exiting)
```
Update your soundcloud-python lib

**Comment by flyingrub** [comment]
i missclicked ...

**Comment by xnrx** [comment]
```
[music/like] pip3.5 install soundcloud --upgrade
Requirement already up-to-date: soundcloud in /usr/lib/python3.5/site-packages
Requirement already up-to-date: fudge>=1.0.3 in /usr/lib/python3.5/site-packages (from soundcloud)
Requirement already up-to-date: requests>=0.14.0 in /usr/lib/python3.5/site-packages (from soundcloud)
Requirement already up-to-date: simplejson>=2.0 in /usr/lib/python3.5/site-packages (from soundcloud)
```
all my dependencies is up-to-date

**Comment by xnrx** [comment]
```
pip list
args (0.1.0)
chardet (2.3.0)
clint (0.5.1)
docopt (0.6.2)
fudge (1.1.0)
mutagen (1.31)
packaging (16.1)
pip (8.0.2)
pyalsaaudio (0.8.2)
pygobject (3.18.2)
pyparsing (2.1.0)
pyxdg (0.25)
ranger (1.7.2)
requests (2.9.1)
scdl (1.4.1)
setuptools (20.0)
simplejson (3.8.1)
six (1.10.0)
soundcloud (0.5.0)
termcolor (1.1.0)
urllib3 (1.14)
wget (3.2)
```

**Comment by flyingrub** [comment]
mmh it was me that is on an outdated version...

**Comment by flyingrub** [comment]
all the switch to dict is unneeded :(...

**Comment by xnrx** [comment]
tell me your soundcloud python lib version, please. i want to use it temporary.

**Comment by flyingrub** [comment]
it works well with 0.4.1

**Comment by xnrx** [comment]
I got it work, but errno104 still exists.

Can [this](http://stackoverflow.com/a/20568874) help somehow?

**Comment by flyingrub** [comment]
i cannot reproduce this error.. i don't have a clue. :/

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/c8c5ff0f2854a4313d9c8f4fcdde95d45111d35f should fix the issue with likes.

**Comment by flyingrub** [comment]
Could you test if it works for you too, and reopen another issue for errno104 ?

**Comment by xnrx** [comment]
Everything works.
