### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by xnrx** [flyingrub/scdl#118]
```
[music/like-test] scdl -l https://soundcloud.com/mattvicemusic/decisions --debug
Soundcloud Downloader
{'--addtofile': False,
 '--debug': True,
 '--error': False,
 '--help': False,
 '--hide-progress': False,
 '--hidewarnings': False,
 '--onlymp3': False,
 '--path': None,
 '--version': False,
 '-a': False,
 '-c': False,
 '-f': False,
 '-l': 'https://soundcloud.com/mattvicemusic/decisions',
 '-o': None,
 '-p': False,
 '-s': False,
 '-t': False,
 'me': False}
Downloading to /data/music/like-test...

Found a track
Downloading Decisions
Downloading the orginal file.
filename : "Decisions.mp3"
[################################] 29/7298 - 00:00:00
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 660, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.5.0', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.5/site-packages/scdl-1.5.0-py3.5.egg/scdl/scdl.py", line 117, in main
  File "/usr/lib/python3.5/site-packages/scdl-1.5.0-py3.5.egg/scdl/scdl.py", line 182, in parse_url
  File "/usr/lib/python3.5/site-packages/scdl-1.5.0-py3.5.egg/scdl/scdl.py", line 391, in download_track
  File "/usr/lib/python3.5/site-packages/clint-0.5.1-py3.5.egg/clint/textui/progress.py", line 115, in bar
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 663, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by xnrx** [comment]
I can download any song now without this error. Seems like they fixed this error.
