### ISSUE TITLE
Installation Issue - PyPanDoc

### ISSUE THREAD

**Issue by 8bitben** [flyingrub/scdl#120]
Hi, I'm getting an installation error installing scdl from pip. Here's the output:

`ben$ pip3 install scdl`
`Collecting scdl`
 `Using cached scdl-1.5.0.post1.tar.gz`
  `  Complete output from command python setup.py egg_info:`
 `   See http://johnmacfarlane.net/pandoc/installing.html`
`    for installation options`
    ---------------------------------------------------------------
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dd/_9k29vwn085fbc13z0mvc6r80000gn/T/pip-build-i5rvk192/scdl/setup.py", line 16, in <module>
        long_description=pypandoc.convert('README.md', 'rst'),
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pypandoc/__init__.py", line 50, in convert
        outputfile=outputfile, filters=filters)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pypandoc/__init__.py", line 70, in _convert
        from_formats, to_formats = get_pandoc_formats()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pypandoc/__init__.py", line 197, in get_pandoc_formats
        _ensure_pandoc_path()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pypandoc/__init__.py", line 336, in _ensure_pandoc_path
        raise OSError("No pandoc was found: either install pandoc and add it\n"
    OSError: No pandoc was found: either install pandoc and add it
    to your PATH or install pypandoc wheels with included pandoc.
    
    ----------------------------------------
`Command "python setup.py egg_info" failed with error code 1 in ``/private/var/folders/dd/_9k29vwn085fbc13z0mvc6r80000gn/T/pip-build-i5rvk192/scdl`

Issue is on freshly installed OSX 10.11.3 El Capitan. Any ideas? Thanks.

**Comment by 8bitben** [comment]
Sorry, solved by manually installing Pandoc.
