### ISSUE TITLE
-a command provides a ton of errors

### ISSUE THREAD

**Issue by lee12jin** [flyingrub/scdl#123]
`$ scdl -l https://soundcloud.com/lee12jin -ac --addtofile`

Returns the following errors:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/scdl-1.5.0.post1-py3.5.egg/scdl/scdl.py", line 259, in download
    download_track(item)
  File "/usr/local/lib/python3.5/site-packages/scdl-1.5.0.post1-py3.5.egg/scdl/scdl.py", line 348, in download_track
    if track['streamable']:
KeyError: 'streamable'
Track n°2300 of 2301
'streamable'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/scdl-1.5.0.post1-py3.5.egg/scdl/scdl.py", line 259, in download
    download_track(item)
  File "/usr/local/lib/python3.5/site-packages/scdl-1.5.0.post1-py3.5.egg/scdl/scdl.py", line 348, in download_track
    if track['streamable']:
KeyError: 'streamable'
Track n°2301 of 2301
'streamable'`

That is not the root error though. I fixed these keyerrors and it doesn't function the way it should be cause the variable `track` isn't what it should be. Not sure what is the error beyond that.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/49a4f17b5ad37695f11c13f05338cf54a58677a0
