### ISSUE TITLE
403 Client Error: Forbidden

### ISSUE THREAD

**Issue by AlexPoulsen** [flyingrub/scdl#135]
###### 403 Client Error: Forbidden
I get this error on a track with a preview.
This is due to the new Soundcloud Go, which may involve something with licensing certain tracks 
(but this is a remix by a different artist so it shouldn't be considered the original artist's track for profiting from, but that is a different topic for elsewhere)
```
Error resolving url, retrying...
Could not resolve url https://soundcloud.com/alisonwonderland/iwantyou-ganzflip-cdm?in=user1827488/sets/future-trap
403 Client Error: Forbidden
```
I can confirm that downloading _does not work_ even when you subscribe to Soundcloud Go (or use their free trial).

**Comment by AlexPoulsen** [comment]
Just rechecked using the _right_ song (facepalm), can confirm it does not work. Updated

**Comment by robattila128** [comment]
Some songs just don't work :(

```
robby ~/Music/[Pop] Dream/dot $ scdl -l https://soundcloud.com/iamdot/dot-modern-romance-feat-jnthn-stein
Soundcloud Downloader

Error resolving url, retrying...
Could not resolve url https://soundcloud.com/iamdot/dot-modern-romance-feat-jnthn-stein
403 Client Error: Forbidden for url: https://api.soundcloud.com/tracks/256757832?client_id=95a4c0ef214f2a4a0852142807b54b35
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl/scdl.py", line 165, in get_item
    item = client.get('/resolve', url=track_url)
  File "/usr/lib/python3.5/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/lib/python3.5/site-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.soundcloud.com/tracks/256757832?client_id=95a4c0ef214f2a4a0852142807b54b35

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl/scdl.py", line 170, in get_item
    item = client.get('/resolve', url=track_url)
  File "/usr/lib/python3.5/site-packages/soundcloud/client.py", line 133, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/lib/python3.5/site-packages/soundcloud/request.py", line 148, in make_request
    result.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.soundcloud.com/tracks/256757832?client_id=95a4c0ef214f2a4a0852142807b54b35
robby ~/Music/[Pop] Dream/dot $ 
```

**Comment by flyingrub** [comment]
duplicate : https://github.com/flyingrub/scdl/issues/137
