### ISSUE TITLE
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by rhssk** [flyingrub/scdl#137]
*These errors started appearing about 1 week ago (maybe something to do with SC Go update)
*Running scdl v1.5.0-3
*Pretty sure I have all the required dependencies, installed scdl from AUR

Error resolving url, retrying...
Could not resolve url https://soundcloud.com/nickraymondg/kidd-upstairs-x-hippie-sabotage-went-down-thissongissick-exclusive
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl/scdl.py", line 170, in get_item
    item = r.json()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl/scdl.py", line 176, in get_item
    item = r.json()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by shillshocked** [comment]
Latest version installed through github:

scdl -l http://soundcloud.com/david-thulin/episode-144-feat-guest-mix-by-neon-feather-the-reconstruction-with-david-thulin
Soundcloud Downloader

Error resolving url, retrying...
Could not resolve url http://soundcloud.com/david-thulin/episode-144-feat-guest-mix-by-neon-feather-the-reconstruction-with-david-thulin
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl-1.5.0.post3-py3.5.egg/scdl/scdl.py", line 170, in get_item
    item = r.json()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scdl-1.5.0.post3-py3.5.egg/scdl/scdl.py", line 176, in get_item
    item = r.json()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by flyingrub** [comment]
fix reminder : replace the clinet_id by a soundcloud one.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/61479bd7457cf8a6d1fb586eb48c702290f45d26 fixed
