### ISSUE TITLE
Installation failure - Invalid syntax

### ISSUE THREAD

**Issue by 3even** [flyingrub/scdl#14]
$  sudo pip3 install scdl

//////////////////////
 Running setup.py (path:/tmp/pip_build_root/mutagen/setup.py) egg_info for package mutagen
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/mutagen/setup.py", line 227, in <module>
        from mutagen import version_string
      File "mutagen/**init**.py", line 23, in <module>
        from mutagen._util import MutagenError
      File "mutagen/_util.py", line 463
        if c == u"\x00":
                      ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/mutagen/setup.py", line 227, in <module>

```
from mutagen import version_string
```

  File "mutagen/**init**.py", line 23, in <module>

```
from mutagen._util import MutagenError
```

  File "mutagen/_util.py", line 463

```
if c == u"\x00":

              ^
```

SyntaxError: invalid syntax
//////////////////////

Any help would be greatly appreciated!

**Comment by 3even** [comment]
Thanks. That worked.
