### ISSUE TITLE
Whenever i try to run a command i get this python error:

### ISSUE THREAD

**Issue by BlackJoe23** [flyingrub/scdl#141]
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.5.0-3', 'console_scripts', 'scdl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/scdl-v1.5.0_3-py2.7.egg/scdl/scdl.py", line 63
    logger.newline = print
                         ^
SyntaxError: invalid syntax

i have already checked if i have python 2 and 3 installed and i have tried git clone and pip, i'm on Debian jessie

**Comment by flyingrub** [comment]
This soft require python3, you are on python2.7
