### ISSUE TITLE
Downloads with scandinavian characters to CIFS-mounted directory fails

### ISSUE THREAD

**Issue by kobolttti** [flyingrub/scdl#174]
$ pwd
/mnt/cifs/music/_SCDL/temp
$ grep cifs /etc/mtab
//cifs/music /mnt/cifs/music cifs rw,mand,noexec,nosuid,nodev 0 0
$ scdl -l https://soundcloud.com/djorion/puheen-iltapaiva-27122013
Soundcloud Downloader

Starting new HTTPS connection (1): api.soundcloud.com
Found a track
Downloading Yle Puheen Iltapa\u0308iva\u0308 27.12.2013
Downloading the original file.
Starting new HTTPS connection (1): api.soundcloud.com
Starting new HTTP connection (1): cf-media.sndcdn.com
[################################] 27749/27749 - 00:00:12
Traceback (most recent call last):
  File "/usr/lib/python3.4/shutil.py", line 523, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpgn5t9up_' -> '/mnt/cifs/music/_SCDL/temp/puheen iltapäivä 20131227 1810.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.6.3', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 161, in main
    parse_url(arguments['-l'])
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 238, in parse_url
    download_track(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 442, in download_track
    shutil.move(temp.name, os.path.join(os.getcwd(), filename))
  File "/usr/lib/python3.4/shutil.py", line 535, in move
    copy2(src, real_dst)
  File "/usr/lib/python3.4/shutil.py", line 245, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.4/shutil.py", line 109, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/cifs/music/_SCDL/temp/puheen iltapäivä 20131227 1810.mp3'

$ ls -l /tmp/tmpgn5t9up_
-rw------- 1 xxx xxx 28414409 Feb  8 21:49 /tmp/tmpgn5t9up_

Downloading filenames with non-extended ASCII characters only works with this CIFS-mount. Also downloads with extended ASCII characters do work if path is a local HDD or locally mounted USB-drive (ext4).

**Comment by kobolttti** [comment]
Actualy looks Python related problem and not scdl. Sorry.

**Comment by kobolttti** [comment]
Fixes by adding iocharset=iso8859-15 mount option.
