### ISSUE TITLE
SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC

### ISSUE THREAD

**Issue by thomsna** [flyingrub/scdl#181]
I sometimes get this error. I usually retry the download, and the error does not appear.

```
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.6.3', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.5/dist-packages/scdl-1.6.3-py3.5.egg/scdl/scdl.py", line 159, in main
  File "/usr/local/lib/python3.5/dist-packages/scdl-1.6.3-py3.5.egg/scdl/scdl.py", line 239, in parse_url
  File "/usr/local/lib/python3.5/dist-packages/scdl-1.6.3-py3.5.egg/scdl/scdl.py", line 329, in download_playlist
  File "/usr/local/lib/python3.5/dist-packages/scdl-1.6.3-py3.5.egg/scdl/scdl.py", line 437, in download_track
  File "/usr/local/lib/python3.5/dist-packages/clint-0.5.1-py3.5.egg/clint/textui/progress.py", line 115, in bar
  File "/usr/lib/python3/dist-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 353, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 310, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)
```

Info about my config:
```
$ uname -a
Linux 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ openssl version
OpenSSL 1.0.2k  26 Jan 2017
```
```
$ scdl --version
v1.6.3
```

**Comment by flyingrub** [comment]
this error doesn't seems related to scdl but thanks for the report ! :)
