### ISSUE TITLE
Windows  Error : module 'scdl.scdl' has no attribute 'main'

### ISSUE THREAD

**Issue by TehNotorious** [flyingrub/scdl#188]
Everytime i try to run scdl i get this:

c:\Python>scdl me -f
Traceback (most recent call last):
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2299, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'scdl.scdl' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Scripts\scdl-script.py", line 11, in <module>
    load_entry_point('scdl==1.6.4', 'console_scripts', 'scdl')()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2301, in resolve
    raise ImportError(str(exc))
ImportError: module 'scdl.scdl' has no attribute 'main'

**Comment by flyingrub** [comment]
Are you using python3 ?

**Comment by TehNotorious** [comment]
Yes, specifically 3.6.1.

Double checked by running
Python --version

**Comment by flyingrub** [comment]
how did you install scdl ?

**Comment by TehNotorious** [comment]
Dropped scdl master into site packages folder and ran

Pip3 install scdl

I tried running the same command again to check and it tells me all the files already installed

**Comment by flyingrub** [comment]
I don't think you need the scdl master. Could you try to remove it from site-package and just run `pip3 install scdl` ?

**Comment by TehNotorious** [comment]
got it to work. reinstalled python 3.6.1 for a clean install, just ran "pip3 install scdl" and it worked fine. Thank you

**Comment by flyingrub** [comment]
I tried with windows and had the same error but running it with `python -m scdl.scdl [OPTIONS]` worked.

**Comment by flyingrub** [comment]
Closing this one as the fix for this is : `python -m scdl.scdl [OPTIONS]`
