### ISSUE TITLE
"ImportError: No module named configparser"

### ISSUE THREAD

**Issue by Craeewan** [flyingrub/scdl#189]
$ scdl -l https://soundcloud.com/1priincemuzik -a
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/scdl", line 11, in <module>
    load_entry_point('scdl==1.6.4', 'console_scripts', 'scdl')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scdl/scdl.py", line 54, in <module>
    import configparser
ImportError: No module named configparser

**Comment by flyingrub** [comment]
This script only support python3 😎
