### ISSUE TITLE
Attempting to download playlist that has a privated song breaks the download for the playlist and can't continue. 404Client Error: Not found for URL.

### ISSUE THREAD

**Issue by DirkEdge** [flyingrub/scdl#201]
Downloading a playlist, but there is a privated song within that playlist, or is otherwise no longer on soundcloud.  This breaks the download. Attempting to download a playlist will download each song up until the removed song, upon which will terminate the download for the rest of the playlist.

I suggest that either the tool finds a way to "skip" removed songs in playlists, or find a way to manually start downloading from a playlist starting from a certain number. There are still 150 other songs in this playlist I have to download...

    Track n°57
    Downloading crawling in my skinhead
    Traceback (most recent call last):
      File "C:\Users\Suici\AppData\Local\Programs\Python\Python36-32\Scripts\scdl-script.py", line 11, in <module>
    load_entry_point('scdl==1.6.4', 'console_scripts', 'scdl')()
      File "c:\users\suici\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 159, in main
    parse_url(arguments['-l'])
      File "c:\users\suici\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 239, in parse_url
    download_playlist(item)
      File "c:\users\suici\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 329, in download_playlist
    download_track(track_raw, playlist['title'], playlist_file)
      File "c:\users\suici\appdata\local\programs\python\python36-32\lib\site-packages\scdl\scdl.py", line 417, in download_track
    r.raise_for_status()
      File "c:\users\suici\appdata\local\programs\python\python36-32\lib\site-packages\requests\models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.soundcloud.com/tracks/137731705/stream?client_id=a3e059563d7fd3372b49b37f00a00bcf

**Comment by DirkEdge** [comment]
Maybe I'm just ignorant about how something works here?

**Comment by flyingrub** [comment]
You can use the `-o` option to start from a certain number. Or use the `-c` option to download track that are not already downloaded.

**Comment by DirkEdge** [comment]
http://i.imgur.com/fk71ZWo.png

Is there something wrong with my syntax? 

`scdl -l https://soundcloud.com/suicidesnowmen/sets/may-may-cray-may-foor -o 68`

doing this makes the download start at the first track instead of skipping it and going to track no68

**Comment by flyingrub** [comment]
Mmm, this seems like a new issue to open :)

Use the `-c` option then...

Le 17 juil. 2017 23:50, "DirkEdge" <notifications@github.com> a écrit :

http://i.imgur.com/fk71ZWo.png

Is there something wrong with my syntax?

scdl -l https://soundcloud.com/suicidesnowmen/sets/may-may-cray-may-foor -o
68

doing this makes the download start at the first track instead of skipping
it and going to track no68

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/flyingrub/scdl/issues/201#issuecomment-315895672>, or mute
the thread

**Comment by DirkEdge** [comment]
using the -c option still runs me into the original problem, that songs that were removed (from the site) or privated still have a "ghost presence" in the playlist, and the scdl cannot download it because of a 404 error.

The -c option is useful for playlists that i can control, meaning that if i edit the playlist order around that track#, then restart the download, but the download still gets stuck on the removed track.

**Comment by flyingrub** [comment]
I just tried with a test playlist containing a private track, and it is just skipped. :/

**Comment by 1papaya** [comment]
Having the same issue here:

```
$ scdl -l https://soundcloud.com/mikaelmoberg/sets/kygo

Soundcloud Downloader
Error resolving url, retrying...
Found a playlist
Track n°1
Downloading Josefine Bryme - Small Bump (Cover)
[################################] 4038/4038 - 00:00:00
Settings tags...
Josefine Bryme - Small Bump (Cover).mp3 Downloaded.

Track n°2
Downloading Robin Thicke - Feel Good (Oliver Heldens Remix)
[################################] 2492/2492 - 00:00:00
Settings tags...
Robin Thicke - Feel Good (Oliver Heldens Remix).mp3 Downloaded.

Track n°3
Downloading Ed Sheeran - I See Fire (Kygo Remix)
[################################] 4952/4952 - 00:00:00
Settings tags...
Ed Sheeran - I See Fire (Kygo Remix).mp3 Downloaded.

Track n°4
Downloading Seinabo Sey - Younger (Kygo Remix)
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.6.4', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.5/dist-packages/scdl/scdl.py", line 159, in main
    parse_url(arguments['-l'])
  File "/usr/local/lib/python3.5/dist-packages/scdl/scdl.py", line 239, in parse_url
    download_playlist(item)
  File "/usr/local/lib/python3.5/dist-packages/scdl/scdl.py", line 329, in download_playlist
    download_track(track_raw, playlist['title'], playlist_file)
  File "/usr/local/lib/python3.5/dist-packages/scdl/scdl.py", line 417, in download_track
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.soundcloud.com/tracks/125621283/stream?client_id=a3e059563d7fd3372b49b37f00a00bcf
```

**Comment by flyingrub** [comment]
Any update on this one ? Did you retried ? Could you share a command that actually fail?

**Comment by iermentraut** [comment]
Hello,

I have this error:

```
Soundcloud Downloader
From cffi callback <function _verify_callback at 0x7fe78b3ed048>:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'
Error resolving url, retrying...

From cffi callback <function _verify_callback at 0x7ff952fe00d0>:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/igor/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.soundcloud.com', port=443): Max retries exceeded with url: /resolve?url=http://soundcloud.com/plusonemusic/the-kooks-naive&client_id=a3e059563d7fd3372b49b37f00a00bcf (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/scdl/scdl.py", line 214, in get_item
    r = requests.get(item_url, params={'client_id': client_id})
  File "/home/igor/.local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/igor/.local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/igor/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/igor/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/igor/.local/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.soundcloud.com', port=443): Max retries exceeded with url: /resolve?url=http://soundcloud.com/plusonemusic/the-kooks-naive&client_id=a3e059563d7fd3372b49b37f00a00bcf (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'
Failed to get item...
```
