### ISSUE TITLE
Cannot download likes of another user; run into Unauthorized error

### ISSUE THREAD

**Issue by Mopok** [flyingrub/scdl#204]
```
Retrieving all likes of user allgreyeverything...
https://api.soundcloud.com/users/199618237/favorites?limit=200&offset=0
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\Scripts\scdl-script.py", line 11, in <module>
    load_entry_point('scdl==1.6.5', 'console_scripts', 'scdl')()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\scdl-1.6.5-py3.6.egg\scdl\scdl.py", line 159, in main
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\scdl-1.6.5-py3.6.egg\scdl\scdl.py", line 243, in parse_url
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\scdl-1.6.5-py3.6.egg\scdl\scdl.py", line 283, in download
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\scdl-1.6.5-py3.6.egg\scdl\client.py", line 19, in get_collection
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests-2.18.1-py3.6.egg\requests\models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/users/199618237/favorites?limit=200&offset=0&client_id=a06b61f88c8297cc5abe6167a2d4c519&linked_partitioning=1
```

When I try to download someone else's likes, I get an error for not being authorized. I guess it's because the script tries to download them as if I am trying to download my own likes. 

Can't the script treat a likes page as a playlist? For example this URL : https://soundcloud.com/allgreyeverything/likes

Instead of treating it as something different? Likes are public so I shouldn't need authorization to download them.

**Comment by flyingrub** [comment]
`scdl -l https://soundcloud.com/allgreyeverything -f`
works well for me.

**Comment by eranrund** [comment]
I'm also getting 401 running `scdl -f --addtofile -l http://soundcloud.com/eranrund -c`

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/08317287b615a0bcf874de0751238e1184abc599 should fix it

**Comment by eranrund** [comment]
It did. Thanks!

**Comment by Mopok** [comment]
Working thanks!
