### ISSUE TITLE
Python TypeError

### ISSUE THREAD

**Issue by dwd1** [flyingrub/scdl#269]
# scdl -a -c --onlymp3 -l https://soundcloud.com/musickillershungary

Tracks and reposts n°1619 of 2595
Found a track
Downloading Willcox - 2017 0306 23H
int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scdl/scdl.py", line 348, in download
    parse_url(uri)
  File "/usr/local/lib/python3.5/dist-packages/scdl/scdl.py", line 262, in parse_url
    download_track(item)
  File "/usr/local/lib/python3.5/dist-packages/scdl/scdl.py", line 499, in download_track
    total_length = int(r.headers.get('content-length'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Tracks and reposts n°1620 of 2595
Error resolving url, retrying...

**Comment by takelley1** [comment]
I was having the same issue but using the `-d ./` option fixed it for me.
