### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by 10frank10** [flyingrub/scdl#292]
Have used scdl flawlessly before but now seem to be getting 401 client error. Saw this was a similar issue in the Soundcloud Downloader that is part of Youtube DL here on GitHub. Someone was able to resolve the error, but I was unable to replicate the update they pushed when trying to fix scdl. Here is my console output below. 

> Franks-MacBook-Pro-2:~ dank$ scdl -l https://soundcloud.com/holmes-john/jacky-holmes-john-mumma
Soundcloud Downloader
Found a track
Downloading Jacky & Holmes John - Mumma
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/scdl", line 11, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 179, in main
    parse_url(arguments['-l'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 262, in parse_url
    download_track(item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 496, in download_track
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/562174671/stream?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z
Franks-MacBook-Pro-2:~ dank$

**Comment by 10frank10** [comment]
Also wanted to add onto this report that I'm now getting another error while trying to run the same command again. Here's output again 

> Franks-MacBook-Pro-2:~ dank$ scdl -l https://soundcloud.com/jordan-brando/jordan-brando-encode-original-mix-club-sweat
Soundcloud Downloader
Found a track
Downloading Jordan Brando - Encode (Original Mix) [Club Sweat]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/scdl", line 11, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 179, in main
    parse_url(arguments['-l'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 262, in parse_url
    download_track(item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 493, in download_track
    url, params={'client_id': ALT_CLIENT_ID}, stream=True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
Franks-MacBook-Pro-2:~ dank$

**Comment by Davicii-ii** [comment]
**yup** 
`401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/486761280/stream?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z
Traceback (most recent call last):
  File "/home/ayuko/.local/lib/python3.6/site-packages/scdl/scdl.py", line 357, in download
    download_track(item)
  File "/home/ayuko/.local/lib/python3.6/site-packages/scdl/scdl.py", line 496, in download_track
    r.raise_for_status()
  File "/home/ayuko/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/486761280/stream?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z`

**Comment by Davicii-ii** [comment]
Is Soundcloud preventing the downloads bcoz the API isn't available?

**Comment by flyingrub** [comment]
30968bc introduce a fix for this and the issue with unauthorized track since yesterday.
For now there is no progress bar anymore and we need ffmpeg to decode HLS stream.

**Comment by jolespin** [comment]
I also have this error but this fixed it: 

```
pip uninstall scdl
pip install git+https://github.com/flyingrub/scdl
```

**Comment by khamsathous** [comment]
I got that error to go away by updating python, uninstalling, then reinstalling, but I then got a parse error I fixed by 

pip install configparser

but now I have yet another error 

john$ scdl
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 5, in <module>
    from scdl.scdl import main
  File "/usr/local/lib/python2.7/site-packages/scdl/scdl.py", line 73, in <module>
    from scdl import __version__, CLIENT_ID, ALT_CLIENT_ID
ImportError: cannot import name __version__

Anyone know how to fix this?

**Comment by jolespin** [comment]
Oh man, I’ve gotten that error before for a completely different program . Do you use conda by any chance?

**Comment by pyxelr** [comment]
After uninstalling and installing scdl through pip, I got the error in the attached file.
Does anyone know how to go around it?
![2019-12-01_16-01-06](https://user-images.githubusercontent.com/30161753/69915843-ca792700-1453-11ea-9392-f14bceb5cb5a.png)

**Comment by silverbacknet** [comment]
> [30968bc](https://github.com/flyingrub/scdl/commit/30968bc5a19703fcf3332613f96e497e43bd6771) introduce a fix for this and the issue with unauthorized track since a few days.
> For now there is no progress bar anymore and we need ffmpeg to decode HLS stream.

Why pull the enormity of ffmpeg in, and using shell piping instead of its api, when there are already pure-python HLS parsers like https://github.com/globocom/m3u8 ?

**Comment by Davicii-ii** [comment]
> > [30968bc](https://github.com/flyingrub/scdl/commit/30968bc5a19703fcf3332613f96e497e43bd6771) introduce a fix for this and the issue with unauthorized track since a few days.
> > For now there is no progress bar anymore and we need FFmpeg to decode HLS stream.
> 
> Why pull the enormity of FFmpeg in, and using shell piping instead of its API, when there are already pure-python HLS parsers like https://github.com/globocom/m3u8?

i think there's a  ffmpeg lib in python

**Comment by flyingrub** [comment]
> 
> Why pull the enormity of ffmpeg in, and using shell piping instead of its api, when there are already pure-python HLS parsers like https://github.com/globocom/m3u8 ?

Here is a few reasons : 
1. I tried to use the m3u8 python library, which is just a parser for the HLS m3u8 file that contains a bunch of link to 10sec mp3. I tried to concatenate the file directly but apparently they overlap in some way. So you end up with a not so pleasant file that does not correspond to the song you want.
2. I then tried to use ffmpeg which handle everything for us and works perfectly.
3. We could use a python wrapper around it, but why use another dependency, as you would still need ffmpeg anyway ? ;)
4. I develop this script in my free time and when I saw that soundcloud broke the compatibility with my script, I was looking for the easiest, fastest to write, more sustainable fix for it, which I think this commit was.

If you have any idea on how to do this in a cleaner way feel free to open a Pull Request.

**Comment by kris-sum** [comment]
@khamsathous 
> ImportError: cannot import name **version**

I think you're using python 2, not python 3.

**Comment by GloBang** [comment]
@flyingrub yo, what is better to download http_mp3_128 or hls_mp3_128?

**Comment by flyingrub** [comment]
> 
> 
> @flyingrub yo, what is better to download http_mp3_128 or hls_mp3_128?

http_mp3_128 is not available for every track, that is why I am using hls_mp3_128.

**Comment by jorubyp** [comment]
shlex.quote() doesn't seem to be working for me like it is for the rest of you, ampersands in the url are still being treated as control operators.

**Comment by CROSP** [comment]
Check my fork, I replaced quotes from `shlex.quote` to simple hardcoded quotes as a temp solution for windows environment https://github.com/CROSP/scdl

**Comment by jorubyp** [comment]
@CROSP Thanks very much, working here too.

**Comment by MrAureliusR** [comment]
> Check my fork, I replaced quotes from `shlex.quote` to simple hardcoded quotes as a temp solution for the windows environment https://github.com/CROSP/scdl

Your fork is not working for me, getting an ffmpeg File not found error. It seems to be trying to pass this enormous URL as the input to ffmpeg.
`FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -i "https://cf-hls-media.sndcdn.com/playlist/kA27FgKlZ3ow.128.mp3/playlist.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL3BsYXlsaXN0L2tBMjdGZ0tsWjNvdy4xMjgubXAzL3BsYXlsaXN0Lm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzU4NTQ1NTN9fX1dfQ__&Signature=RbNOj8kO5RiZuqqTNHw-TboITGUevi9xJVNJ94IHRc11cvh~Bu974cRJTejZf503DP2xDYLHfylFY5oVIU26EAYLf6xjIbe9reS5vPVJyWq4HDi6fNeZdTVod72FxNDwyImQophfpPRC3Vsvn~id0QAZyQzngF5NY5fgwplrncK3BM~x9DXPpzo9gLRKsvB5y5RPPzB0ELUNIwSzy97~SfLJH3t~6ARs7ww4sEGbn6S-GdSXP2XpU7VzuYD5a9r5KnJWxE28QbH7VCx5fqhiR3mty-Jy6HllVzeN9Xn3f3VtTt6c8Io9QJIZi4GAHN0N8Fi~pwQRg7pjE-xnbN7rsg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ" -c copy "King Of The World.mp3" -loglevel fatal': 'ffmpeg -i "https://cf-hls-media.sndcdn.com/playlist/kA27FgKlZ3ow.128.mp3/playlist.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL3BsYXlsaXN0L2tBMjdGZ0tsWjNvdy4xMjgubXAzL3BsYXlsaXN0Lm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzU4NTQ1NTN9fX1dfQ__&Signature=RbNOj8kO5RiZuqqTNHw-TboITGUevi9xJVNJ94IHRc11cvh~Bu974cRJTejZf503DP2xDYLHfylFY5oVIU26EAYLf6xjIbe9reS5vPVJyWq4HDi6fNeZdTVod72FxNDwyImQophfpPRC3Vsvn~id0QAZyQzngF5NY5fgwplrncK3BM~x9DXPpzo9gLRKsvB5y5RPPzB0ELUNIwSzy97~SfLJH3t~6ARs7ww4sEGbn6S-GdSXP2XpU7VzuYD5a9r5KnJWxE28QbH7VCx5fqhiR3mty-Jy6HllVzeN9Xn3f3VtTt6c8Io9QJIZi4GAHN0N8Fi~pwQRg7pjE-xnbN7rsg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ" -c copy "King Of The World.mp3" -loglevel fatal'`

**Comment by GiovanH** [comment]
The workaround with ffmpeg doesn't work for me at all; ffmpeg fails and also seems to try to execute raw shell code?

```
$ scdl -l https://soundcloud.com/aradiasings -t
Soundcloud Downloader
Found a user profile
Retrieving all uploaded tracks of user broadway aradia^2...
Retrieved 5 uploaded tracks
Uploaded tracks n°1 of 5
Retrieving more info on the track
Downloading while my b0dy sleeps
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
'https://cf-hls-media.sndcdn.com/playlist/h3Q2BY2JAzu9.128.mp3/playlist.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL3BsYXlsaXN0L2gzUTJCWTJKQXp1OS4xMjgubXAzL3BsYXlsaXN0Lm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzY5NjU5MTF9fX1dfQ__: No such file or directory
'Signature' is not recognized as an internal or external command,
operable program or batch file.
'Key-Pair-Id' is not recognized as an internal or external command,
operable program or batch file.
Setting tags...
Error trying to set the tags...
Cannot update utime of file
```

**Comment by CristianNanan** [comment]
Here are the steps I had to take to get this working again:
1) uninstall the current version
pip uninstall scdl

2) install CROSP's fork
pip install git+https://github.com/CROSP/scdl

3) download ffmpeg and add the bin folder to your path
https://www.ffmpeg.org/download.html

After doing this it works for me.

**Comment by UkwaA** [comment]
> Here are the steps I had to take to get this working again:
> 
> 1. uninstall the current version
>    pip uninstall scdl
> 2. install CROSP's fork
>    pip install git+https://github.com/CROSP/scdl
> 3. download ffmpeg and add the bin folder to your path
>    https://www.ffmpeg.org/download.html
> 
> After doing this it works for me.

I'm confused on what you mean by adding the bin folder to my path. Which path? My user path or the scdl path?

**Comment by silverbacknet** [comment]
> Edit: Nvm I figured out where to get the bin file from, my only remaining question is which path to put it in

Anywhere that scdl can see it from. You can even drop scdl and everything in bin into the same folder and scdl will use it just fine. ffmpeg's very useful in general, so I have it in the system path; the user path would work, except for anything run as administrator. (I actually have some tricky junctions set up to go to different folders depending on x86 or x64, but practically everything's x64 now anyway.)

Oh, and by "path" we mean the thing you get to when you right click the start button, choose settings, click system info on the top right, click advanced system settings on the left, and open the "Environment Variables." One of them is PATH, and the system combines the system and user version to look up missing files before it fails.

Some installers of ffmpeg will do the add to path for you, but I forget which ones.

**Comment by mavieth** [comment]
I opened up a PR that appears to fix these issues. https://github.com/flyingrub/scdl/pull/304

**Comment by imranhafiz** [comment]
> Here are the steps I had to take to get this working again:
> 
> 1. uninstall the current version
>    pip uninstall scdl
> 2. install CROSP's fork
>    pip install git+https://github.com/CROSP/scdl
> 3. download ffmpeg and add the bin folder to your path
>    https://www.ffmpeg.org/download.html
> 
> After doing this it works for me.

thanks to all of you for your help, particularly @flyingrub and @CROSP!

I'm definitely a beginner here, having the same issue but on Mac.  I'm using pip3 instead of pip (because the Mac's system pip is 2.7, whereas the new python i've installed is now 3.8).

What is ffmpeg, and how do I install it?  Moreover, how do I "add the bin folder to my path" on Mac?  Currently, SCDL seems to be downloading to my user folder on Mac.

**Comment by flyingrub** [comment]
you should be install to run `brew install ffmpeg` after having installed https://brew.sh/

**Comment by imranhafiz** [comment]
> you should be install to run `brew install ffmpeg` after having installed https://brew.sh/

done!  ffmpeg is installed now, through homebrew.  How do I set the ffmpeg's bin file into scdl's path? more specifically, what should I type into terminal in order to get scdl to see ffmpeg?

currently, scdl is outputting to my username (where my application folder is) on my Mac (running mojave 10.14.5).

**Comment by flyingrub** [comment]
Latest commit on master should fix those issues

**Comment by GiovanH** [comment]
Issue unresolved, still gives error on latest version:
```
Downloading xxx
401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/xxx/stream?client_id=xxx
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\scdl-1.6.11-py3.7.egg\scdl\scdl.py", line 357, in download
    download_track(item)
  File "c:\program files\python37\lib\site-packages\scdl-1.6.11-py3.7.egg\scdl\scdl.py", line 496, in download_track
    r.raise_for_status()
  File "c:\program files\python37\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

**Comment by TheMasterDan** [comment]
pip uninstall scdl
apt install python3-pip --reinstall
pip3 uninstall scdl
pip3 install git+https://github.com/flyingrub/scdl
scdl
done.
