### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by no95typem** [flyingrub/scdl#294]
After installing the version from github (due to  #292 ).

$ scdl -l https://soundcloud.com/user/sets/myset
Soundcloud Downloader
Found a playlist
Track n°1
Retrieving more info on the track
Downloading TrackName
Downloading the original file.
Traceback (most recent call last):
  File "/home/user/.local/bin/scdl", line 11, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "/home/user/.local/lib/python3.6/site-packages/scdl/scdl.py", line 179, in main
    parse_url(arguments['-l'])
  File "/home/user/.local/lib/python3.6/site-packages/scdl/scdl.py", line 265, in parse_url
    download_playlist(item)
  File "/home/user/.local/lib/python3.6/site-packages/scdl/scdl.py", line 386, in download_playlist
    download_track(track_raw, playlist['title'], playlist_file)
  File "/home/user/.local/lib/python3.6/site-packages/scdl/scdl.py", line 540, in download_track
    filename = download_original_file(track, title)
  File "/home/user/.local/lib/python3.6/site-packages/scdl/scdl.py", line 449, in download_original_file
    filename = re.findall("filename=(.+)", d)[0][1:-1]
  File "/usr/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object

**Comment by kellergoech** [comment]
Hello, i found the problem and also a solution:

in scdl.py Line 446, add:

`if r.status_code == 404:
 logger.info('Could not get name from stream - using basic name')
 return None`

Can in change this, or someone of the creators?

**Comment by no95typem** [comment]
> Hello, i found the problem and also a solution:
> 
> in scdl.py Line 446, add:
> 
> `if r.status_code == 404: logger.info('Could not get name from stream - using basic name') return None`
> 
> Can in change this, or someone of the creators?

Yes, it works! Thank you!
