### ISSUE TITLE
Playlist download fails when a track already downloaded

### ISSUE THREAD

**Issue by ligeia** [flyingrub/scdl#297]
scdl -l http://soundcloud.com/myluckypack/sets/water-november-2019 -c --addtofile --onlymp3 --path /mnt/c/Users/neilm/Music/playlists/ --download-archive archive.txt --min-size 800k

Soundcloud Downloader
Found a playlist
Track n°1
Retrieving more info on the track
Downloading Shöckface & So Sus - Tribe
Track "Shöckface & So Sus - Tribe" already downloaded.
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.5/dist-packages/scdl-1.6.12-py3.5.egg/scdl/scdl.py", line 179, in main
  File "/usr/local/lib/python3.5/dist-packages/scdl-1.6.12-py3.5.egg/scdl/scdl.py", line 265, in parse_url
  File "/usr/local/lib/python3.5/dist-packages/scdl-1.6.12-py3.5.egg/scdl/scdl.py", line 386, in download_playlist
  File "/usr/local/lib/python3.5/dist-packages/scdl-1.6.12-py3.5.egg/scdl/scdl.py", line 558, in download_track
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by PSandro** [comment]
I'm getting the same error when downloading a playlist.
`$ scdl -c -l https://soundcloud.com/sandrosplaylist/sets/dj
Soundcloud Downloader
Found a playlist
Track n°1
Retrieving more info on the track
Downloading Tujamo - Booty Bounce (Original Mix)
Track "Tujamo - Booty Bounce (Original Mix)" already downloaded.
Traceback (most recent call last):
  File "/home/sandro/.local/bin/scdl", line 10, in <module>
    sys.exit(main())
  File "/home/sandro/.local/lib/python3.7/site-packages/scdl/scdl.py", line 179, in main
    parse_url(arguments['-l'])
  File "/home/sandro/.local/lib/python3.7/site-packages/scdl/scdl.py", line 265, in parse_url
    download_playlist(item)
  File "/home/sandro/.local/lib/python3.7/site-packages/scdl/scdl.py", line 386, in download_playlist
    download_track(track_raw, playlist['title'], playlist_file)
  File "/home/sandro/.local/lib/python3.7/site-packages/scdl/scdl.py", line 558, in download_track
    if filename.endswith('.mp3') or filename.endswith('.flac'):
AttributeError: 'NoneType' object has no attribute 'endswith'
`

**Comment by mavieth** [comment]
Opened a PR that may fix some of these issues: https://github.com/flyingrub/scdl/pull/304

**Comment by flyingrub** [comment]
This is now fixed in the master branch
