### ISSUE TITLE
Error when downloading a track

### ISSUE THREAD

**Issue by lzrdblzzrd** [flyingrub/scdl#301]
```
Likes n°27 of 517
Retrieving more info on the track
Downloading VSN7 - Сны (feat. inchantix)
[WinError 2] Не удается найти указанный файл
Traceback (most recent call last):
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\site-packages\scdl\scdl.py", line 357, in download
    download_track(item)
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\site-packages\scdl\scdl.py", line 544, in download_track
    filename = download_hls_mp3(track, title)
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\site-packages\scdl\scdl.py", line 514, in download_hls_mp3
    res = subprocess.call(
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл
Likes n°28 of 517
Retrieving more info on the track
Downloading rolling stoner w/ PAVELLL
[WinError 2] Не удается найти указанный файл
Traceback (most recent call last):
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\site-packages\scdl\scdl.py", line 357, in download
    download_track(item)
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\site-packages\scdl\scdl.py", line 544, in download_track
    filename = download_hls_mp3(track, title)
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\site-packages\scdl\scdl.py", line 514, in download_hls_mp3
    res = subprocess.call(
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\lzrdblzzrd\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл
Likes n°29 of 517
Retrieving more info on the track
Downloading Kryptik Pimpz Ft. KRXXP$XT (Prod. $mokegod)
Downloading the original file.
```

I installed SCDL from the CROSP repository, added ffmpeg to the path, but still get an error. Only 1-2 files are downloaded and there are errors that are written above.

**Comment by mavieth** [comment]
This pull request may fix your issue: https://github.com/flyingrub/scdl/pull/304

**Comment by lzrdblzzrd** [comment]
Everything worked after your #1d0776c commit.
