### ISSUE TITLE
Recent merge doesn't work on Ubuntu

### ISSUE THREAD

**Issue by zihangg** [flyingrub/scdl#306]
Both playlist downloading and normal track downloading provides an error.

Traceback (most recent call last):                                                                                                                                                                        File "/home/zh/.local/bin/scdl", line 11, in <module>                                                                                                                                                     load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()                                                                                                                                         File "/home/zh/.local/lib/python3.6/site-packages/scdl/scdl.py", line 180, in main                                                                                                                        parse_url(arguments['-l'])                                                                                                                                                                            File "/home/zh/.local/lib/python3.6/site-packages/scdl/scdl.py", line 263, in parse_url                                                                                                                   download_track(item)                                                                                                                                                                                  File "/home/zh/.local/lib/python3.6/site-packages/scdl/scdl.py", line 548, in download_track                                                                                                              filename = download_hls_mp3(track, title)                                                                                                                                                             File "/home/zh/.local/lib/python3.6/site-packages/scdl/scdl.py", line 521, in download_hls_mp3                                                                                                            '"' + filename + '"'                                                                                                                                                                                  File "/usr/lib/python3.6/subprocess.py", line 287, in call                                                                                                                                                with Popen(*popenargs, **kwargs) as p:                                                                                                                                                                File "/usr/lib/python3.6/subprocess.py", line 729, in __init__                                                                                                                                            restore_signals, start_new_session)                                                                                                                                                                   File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child                                                                                                                                     raise child_exception_type(errno_num, err_msg, err_filename)                                                                                                                                        OSError: [Errno 36] File name too long: 'ffmpeg -i "https://cf-hls-media.sndcdn.com/playlist/KveWcBZlm2tF.128.mp3/playlist.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL3BsYXlsaXN0L0t2ZVdjQlpsbTJ0Ri4xMjgubXAzL3BsYXlsaXN0Lm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzkxNTI3NDZ9fX1dfQ__&Signature=aQ6w7F4hy8JvjLV3zL32FB0YwuPCAKIj769S7TEcml6f8wuP0KCQquYCyfqpNx-xOLKqKrJB5QAOuPQynkRLzG49Kcvy2BaMk7qwaZ~85bsh4pTCvM9U0~0iywbeJBbmrgkOO3WykPJNrVYH6oOw817ajO9h-xn~e2jMVP8uxDDfkUXhsCoEdUBUw6XLs2PjdKiMXIq0Hpput-UgpTatyuAH~tMLpICFbgDWICFNBqVNN8HR7ji2RPpRTZ49XGOUgOUmeMMdH7DkBc5Npaj2IJXsebRducdy5efPJmvisH7Lj~z6XWcu56WBG4dDAvxlnbh55phgNRmS3bCikdaCVg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ" -c copy "Suicidal.mp3" -loglevel fatal'

**Comment by mavieth** [comment]
Try this: https://github.com/flyingrub/scdl/pull/305#issuecomment-575003665

I opened a PR with some fixes https://github.com/flyingrub/scdl/pull/304

**Comment by zihangg** [comment]
Tested, and works. Thanks.

**Comment by flyingrub** [comment]
Our master branch should work fine now too
