### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by jimmynames** [flyingrub/scdl#311]
``` ▶ scdl -l https://soundcloud.com/names-fm/sets/soundcloud-weekly994 -c
Soundcloud Downloader
Found a playlist
Track n°1
Retrieving more info on the track
Downloading join me (raw)
Track "join me (raw)" already downloaded.
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 11, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.7/site-packages/scdl-1.6.12-py3.7.egg/scdl/scdl.py", line 179, in main
  File "/usr/local/lib/python3.7/site-packages/scdl-1.6.12-py3.7.egg/scdl/scdl.py", line 265, in parse_url
  File "/usr/local/lib/python3.7/site-packages/scdl-1.6.12-py3.7.egg/scdl/scdl.py", line 386, in download_playlist
  File "/usr/local/lib/python3.7/site-packages/scdl-1.6.12-py3.7.egg/scdl/scdl.py", line 558, in download_track
AttributeError: 'NoneType' object has no attribute 'endswith'
 ```

**Comment by jimmynames** [comment]
Have tried unisntalling and reinstalling :/ any help greatly appreiciated

**Comment by jimmynames** [comment]
uninstalling via PIP and PIP3 resolved =}
