### ISSUE TITLE
Track download in set fails with KeyError: 'title'

### ISSUE THREAD

**Issue by stoically** [flyingrub/scdl#314]
`scdl -l https://soundcloud.com/becca-peleschak/sets/house-electronic`

fails with

```
{'comment_count': 22, 'downloadable': False, 'release': None, 'created_at': '2017/04/13 17:14:42 +0000', 'description': "Here's our take on a stellar track by Sylvan Esso, and is now available as a free download.  Enjoy!", 'original_content_size': 74992368, 'title': 'Sylvan Esso - Die Young (Medicinne Remix)- Free Download', 'track_type': None, 'duration': 425025, 'video_url': None, 'original_format': 'wav', 'artwork_url': 'https://i1.sndcdn.com/artworks-000217645503-yszj90-large.jpg', 'streamable': True, 'tag_list': '"Deep House" House "Sylvan Esso" "Medicinne " Remix', 'release_month': 4, 'genre': 'Deep House', 'release_day': 11, 'id': 317527477, 'state': 'finished', 'reposts_count': 0, 'last_modified': '2019/06/14 16:49:54 +0000', 'label_name': None, 'commentable': True, 'bpm': None, 'policy': 'ALLOW', 'favoritings_count': 756, 'kind': 'track', 'purchase_url': 'https://www.toneden.io/medicinne/post/sylvan-esso-die-young-medicinne-remix', 'release_year': 2017, 'key_signature': None, 'isrc': None, 'sharing': 'public', 'uri': 'https://api.soundcloud.com/tracks/317527477', 'download_count': 0, 'likes_count': 756, 'license': 'cc-by-nc-sa', 'purchase_title': 'DOWNLOAD NOW', 'user_id': 45230230, 'embeddable_by': 'all', 'monetization_model': 'NOT_APPLICABLE', 'waveform_url': 'https://w1.sndcdn.com/pIXbjiow1RbH_m.png', 'permalink': 'sylvan-esso-die-young-medicinne-remix', 'permalink_url': 'https://soundcloud.com/medicinne/sylvan-esso-die-young-medicinne-remix', 'user': {'id': 45230230, 'kind': 'user', 'permalink': 'medicinne', 'username': 'Medicinne', 'last_modified': '2019/06/14 16:49:50 +0000', 'uri': 'https://api.soundcloud.com/users/45230230', 'permalink_url': 'https://soundcloud.com/medicinne', 'avatar_url': 'https://i1.sndcdn.com/avatars-000412477506-8imrsz-large.jpg'}, 'label_id': None, 'stream_url': 'https://api.soundcloud.com/tracks/317527477/stream', 'playback_count': 0}
Track n°71
Retrieving more info on the track
{}
Traceback (most recent call last):
  File "/home/user/.local/bin/scdl", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/scdl/scdl.py", line 180, in main
    parse_url(arguments['-l'])
  File "/home/user/.local/lib/python3.7/site-packages/scdl/scdl.py", line 266, in parse_url
    download_playlist(item)
  File "/home/user/.local/lib/python3.7/site-packages/scdl/scdl.py", line 387, in download_playlist
    download_track(track_raw, playlist['title'], playlist_file)
  File "/home/user/.local/lib/python3.7/site-packages/scdl/scdl.py", line 532, in download_track
    title = track_info['title']
KeyError: 'title'

```

Apparently it tries to download a track that isn't in the set, since I can't find the title from the JSON dump in there.

Workaround:

```diff
diff --git a/scdl/scdl.py b/scdl/scdl.py
index c8b1072..52cf23d 100755
--- a/scdl/scdl.py
+++ b/scdl/scdl.py
@@ -527,9 +527,14 @@ def download_track(track, playlist_name=None, playlist_file=None):
     Downloads a track
     """
     global arguments
-    track = get_track_info(track['id'])
-    title = track['title']
-    title = title.encode('utf-8', 'ignore').decode('utf8')
+    track = get_track(track['id'])
+    if track:
+        title = track['title']
+        title = title.encode('utf-8', 'ignore').decode('utf8')
+    else:
+        logger.error('Could not get track info')
+        return
+
     logger.info('Downloading {0}'.format(title))
 
     # Not streamable
```

**Comment by flyingrub** [comment]
My latest commit upgrading the api endpoint to v2 fixes this one too
