### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by jsultan2323** [flyingrub/scdl#340]
I am retrieving this error:

$ scdl -l https://soundcloud.com/mmxvmusic/sets/plugged-009
Soundcloud Downloader
Found a playlist
Track n▒1
Downloading Freaky & Destroy3r - Flame (feat. Jessie G)
Traceback (most recent call last):
  File "C:\Progam Files\Python\Python38-32\Scripts\scdl-script.py", line 11, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "c:\progam files\python\python38-32\lib\site-packages\scdl\scdl.py", line 182, in main
    parse_url(arguments['-l'])
  File "c:\progam files\python\python38-32\lib\site-packages\scdl\scdl.py", line 277, in parse_url
    download_playlist(item)
  File "c:\progam files\python\python38-32\lib\site-packages\scdl\scdl.py", line 406, in download_playlist
    download_track(track_raw, playlist_info)
  File "c:\progam files\python\python38-32\lib\site-packages\scdl\scdl.py", line 571, in download_track
    filename = download_hls_mp3(track, title)
  File "c:\progam files\python\python38-32\lib\site-packages\scdl\scdl.py", line 541, in download_hls_mp3
    subprocess.call(['ffmpeg', '-i', url, '-c', 'copy', filename_path, '-loglevel', 'fatal'])
  File "c:\progam files\python\python38-32\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\progam files\python\python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\progam files\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Not sure what the issue is here.

**Comment by maxtinion** [comment]
@jsultan2323 I ran into the same exact issue and I solved it by installing FFmpeg and adding it to the path.

**Comment by flyingrub** [comment]
Install ffmpeg and add it to the path as stated above.
