### ISSUE TITLE
Failed to get item

### ISSUE THREAD

**Issue by haberturdeur** [flyingrub/scdl#346]
Hi I tried to use this program, for some reason though it didn't work. Here is debug info:
```bash
tom@tom-LIFEBOOK-E744 ~ scdl -l https://soundcloud.com/my-name -f --debug
Soundcloud Downloader
{'--addtimestamp': False,
 '--addtofile': False,
 '--debug': True,
 '--download-archive': None,
 '--error': False,
 '--extract-artist': False,
 '--flac': False,
 '--help': False,
 '--hide-progress': False,
 '--hidewarnings': False,
 '--max-size': None,
 '--min-size': None,
 '--no-playlist-folder': False,
 '--onlymp3': False,
 '--path': None,
 '--remove': False,
 '--version': False,
 '-C': False,
 '-a': False,
 '-c': False,
 '-f': True,
 '-l': 'https://soundcloud.com/my-name',
 '-m': False,
 '-o': None,
 '-p': False,
 '-s': False,
 '-t': False,
 'me': False}
Downloading to /home/tom...
https://api.soundcloud.com/resolve?url=https://soundcloud.com/my-name&client_id=a3e059563d7fd3372b49b37f00a00bcf
https://api.soundcloud.com/resolve?url=https://soundcloud.com/my-name&client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z
Failed to get item...
None

```

Thanks in advance!

**Comment by durgenheim** [comment]
:( i get the same thing

c:\>scdl -l https://soundcloud.com/luke-pankau -f --debug
Soundcloud Downloader
{'--addtimestamp': False,
 '--addtofile': False,
 '--debug': True,
 '--download-archive': None,
 '--error': False,
 '--extract-artist': False,
 '--flac': False,
 '--help': False,
 '--hide-progress': False,
 '--hidewarnings': False,
 '--max-size': None,
 '--min-size': None,
 '--no-playlist-folder': False,
 '--onlymp3': False,
 '--path': None,
 '--remove': False,
 '--version': False,
 '-C': False,
 '-a': False,
 '-c': False,
 '-f': True,
 '-l': 'https://soundcloud.com/luke-pankau',
 '-m': False,
 '-o': None,
 '-p': False,
 '-s': False,
 '-t': False,
 'me': False}
Downloading to c:\...
https://api.soundcloud.com/resolve?url=https://soundcloud.com/luke-pankau&client_id=a3e059563d7fd3372b49b37f00a00bcf
https://api.soundcloud.com/resolve?url=https://soundcloud.com/luke-pankau&client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z
Failed to get item...
None

any suggestions ?

**Comment by ligeia** [comment]
Same issue for me, same output as durgenheim.

**Comment by NK308** [comment]
Me too. Since quite a few months.

**Comment by flyingrub** [comment]
Can I ask from which country you are trying ?

**Comment by haberturdeur** [comment]
Czech republic

**Comment by NK308** [comment]
Germany

**Comment by giubil** [comment]
Had the same issue, it's because the pip package is outdated. You need to install it from the repo, as per the [install instructions ](https://github.com/flyingrub/scdl/wiki/Installation-Instruction): 

```
The pip repository version of scdl is outdated you will have to install it directly from the github repo :

pip3 install git+https://github.com/flyingrub/scdl
```

**Comment by winterflags** [comment]
> Had the same issue, it's because the pip package is outdated. You need to install it from the repo, as per the [install instructions ](https://github.com/flyingrub/scdl/wiki/Installation-Instruction):
> 
> ```
> The pip repository version of scdl is outdated you will have to install it directly from the github repo :
> 
> pip3 install git+https://github.com/flyingrub/scdl
> ```

Works. I had to uninstall scdl from the pip repo via pip3 before I could run this command however:

```
pip3 uninstall scdl
pip3 install git+https://github.com/flyingrub/scdl
```

**Comment by ProdByJuliot** [comment]
I'm running 1.6.12 and I get the same issue. I installed it from the repo as far as I know.
`scdl -l https://soundcloud.com/juliotmusic -f -c --addtimestamp --max-size 75mb`
returms `failed to get item`

**Comment by ProdByJuliot** [comment]
I installed from the repo and I can't seem to get any different from these two responses
I'm not sure how much of it is operator error vs soundcloud not cooperating.
```
scdl -l https://soundcloud.com/juliotmusic -f -c --addtimestamp --addtofile --max-size 75mb
Soundcloud Downloader
Failed to get item...
```
```
scdl -l https://soundcloud.com/juliotmusic -f --addtimestamp --addtofile
Soundcloud Downloader
Found a user profile
Retrieving all likes of user crsn...
Traceback (most recent call last):
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\Scripts\scdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')())
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\scdl\scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\scdl\scdl.py", line 284, in parse_url
    download(item, 'favorites', 'likes')
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\scdl\scdl.py", line 356, in download
    resources = client.get_collection(dl_url, token)
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\scdl\client.py", line 19, in get_collection
    response.raise_for_status()
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-v2.soundcloud.com/users/71608215/track_likes?limit=200&client_id=a3e059563d7fd3372b49b37f00a00bcf&linked_partitioning=1&oauth_token=https%3A%2F%2Fsoundcloud.com%2Fjuliotmusic
```

**Comment by Dollabilliam** [comment]
I've also been facing a wide range of issues. I've uninstalled the application and reinstalled it with the suggested way of doing it ```pip3 install git+https://github.com/flyingrub/scdl```

Perhaps the return JSON has changed?

Here are some of the errors I've faced:

```
scdl -l https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500 -c --debug
. {return JSON containing track data}
.
.
Track n°1
Downloading Chris Lee (Li Yuchun 李宇春) - Only You (Clark Remix)
Downloading the original file.
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 280, in parse_url
    download_playlist(item)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 413, in download_playlist
    download_track(track_raw, playlist_info)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 576, in download_track
    filename, is_already_downloaded = download_original_file(track, title)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 470, in download_original_file
    r = requests.get(r.json()['redirectUri'], stream=True)
KeyError: 'redirectUri'
```

here's the same command from this morning:

```
scdl -l https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500 -c --debug
Soundcloud Downloader
{'--addtimestamp': False,
 '--addtofile': False,
 '--debug': True,
 '--download-archive': None,
 '--error': False,
 '--extract-artist': False,
 '--flac': False,
 '--force-metadata': False,
 '--help': False,
 '--hide-progress': False,
 '--hidewarnings': False,
 '--max-size': None,
 '--min-size': None,
 '--no-album-tag': False,
 '--no-playlist-folder': False,
 '--onlymp3': False,
 '--path': None,
 '--remove': False,
 '--version': False,
 '-C': False,
 '-a': False,
 '-c': True,
 '-f': False,
 '-l': 'https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500',
 '-m': False,
 '-n': None,
 '-o': None,
 '-p': False,
 '-s': False,
 '-t': False,
 'me': False}
Downloading to /Users/billy/Soundcloud...
https://api-v2.soundcloud.com/resolve?url=https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500&client_id=a3e059563d7fd3372b49b37f00a00bcf
https://api-v2.soundcloud.com/resolve?url=https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500&client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z
Failed to get item...
None
```

also from this morning but just for one track

```
scdl -l https://soundcloud.com/lockedclub/locked-club-tanzevat-edit
Soundcloud Downloader
Found a track
Downloading Locked Club - Tanzevat Edit
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 277, in parse_url
    download_track(item)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 579, in download_track
    filename, is_already_downloaded = download_hls_mp3(track, title)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 545, in download_hls_mp3
    url = get_track_m3u8(track)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 534, in get_track_m3u8
    return r.json()['url']
KeyError: 'url'
```

Anyways, I'll try taking a deeper look into this this weekend
