### ISSUE TITLE
Error while retrieving more info about track

### ISSUE THREAD

**Issue by silverfox0000** [flyingrub/scdl#375]
```
Traceback (most recent call last):
  File "C:\Users\******\AppData\Local\Programs\Python\Python39\Scripts\scdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')())
  File "c:\users\******\appdata\local\programs\python\python39\lib\site-packages\scdl\scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "c:\users\******\appdata\local\programs\python\python39\lib\site-packages\scdl\scdl.py", line 280, in parse_url
    download_playlist(item)
  File "c:\users\******\appdata\local\programs\python\python39\lib\site-packages\scdl\scdl.py", line 413, in download_playlist
    download_track(track_raw, playlist_info)
  File "c:\users\******\appdata\local\programs\python\python39\lib\site-packages\scdl\scdl.py", line 558, in download_track
    title = track['title']
KeyError: 'title'
```

Debug output
```
Track n°6
Retrieving more info on the track
{}
```

It will recive empty json

**Comment by jz1** [comment]
Please provide soundcloud link as well
