### ISSUE TITLE
End User somehow messing up the path or something

### ISSUE THREAD

**Issue by GrateBrittan** [flyingrub/scdl#378]
Okay so basically

```
Traceback (most recent call last):
  File "C:\Users\End User\AppData\Local\Programs\Python\Python38-32\Scripts\scdl-script.py", line 11, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "c:\users\end user\appdata\local\programs\python\python38-32\lib\site-packages\scdl\scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "c:\users\end user\appdata\local\programs\python\python38-32\lib\site-packages\scdl\scdl.py", line 277, in parse_url
    download_track(item)
  File "c:\users\end user\appdata\local\programs\python\python38-32\lib\site-packages\scdl\scdl.py", line 579, in download_track
    filename, is_already_downloaded = download_hls_mp3(track, title)
  File "c:\users\end user\appdata\local\programs\python\python38-32\lib\site-packages\scdl\scdl.py", line 548, in download_hls_mp3
    subprocess.call(['ffmpeg', '-i', url, '-c', 'copy', filename_path, '-loglevel', 'fatal'])
  File "c:\users\end user\appdata\local\programs\python\python38-32\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\end user\appdata\local\programs\python\python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\end user\appdata\local\programs\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by 7x11x13** [comment]
Looks like you don't have ffmpeg installed

**Comment by GrateBrittan** [comment]
weird, I could have sworn I installed ffmpeg for loading video in to ableton

**Comment by 7x11x13** [comment]
You may have ffmpeg on your system somewhere, but you need to be able to run `ffmpeg` from the command line (i.e. the path to ffmpeg must be in your PATH environment variable)

**Comment by GrateBrittan** [comment]
Cool cool, thank you
