### ISSUE TITLE
 403 Client Error: Forbidden for url: https://api-v2.soundcloud...

### ISSUE THREAD

**Issue by jamesryan-dev** [flyingrub/scdl#386]
```
╰─ scdl -l https://soundcloud.com/names-fm -f
Soundcloud Downloader
Found a user profile
Retrieving all likes of user names...
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 284, in parse_url
    download(item, 'favorites', 'likes')
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 356, in download
    resources = client.get_collection(dl_url, token)
  File "/usr/local/lib/python3.9/site-packages/scdl/client.py", line 19, in get_collection
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api-v2.soundcloud.com/users/36303556/track_likes?offset=1630499822322690&limit=200&client_id=a3e059563d7fd3372b49b37f00a00bcf&linked_partitioning=1
```

receiving this error, have tried updating `scdl` 

more error reporting in hopes of fix but open to ideas on how to resolve on my end?

**Comment by 7x11x13** [comment]
Hi this should be fixed now
