### ISSUE TITLE
KeyError: client_id

### ISSUE THREAD

**Issue by shejan0** [flyingrub/scdl#387]
Hi, I updated to the latest version of SoundCloud Downloader (2.2.1) from the upgrade instruction after getting url errors that have been reported, but with the new version I just get:

```
E:\MoxiFloxi\SoundCloud>scdl -l https://soundcloud.com/moxifloxi -t -c --download-archive DOWNLOADED.txt 
Soundcloud Downloader
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\scdl-script.py", line 11, in <module>     
    load_entry_point('scdl==2.2.1', 'console_scripts', 'scdl')()
  File "C:\Program Files\Python38\lib\site-packages\scdl\scdl.py", line 141, in main
    arguments["--client-id"] = config["scdl"]["client_id"]
  File "C:\Program Files\Python38\lib\configparser.py", line 1254, in __getitem__   
    raise KeyError(key)
KeyError: 'client_id'
```
I am unsure if my command is off or set up incorrectly.

**Comment by 7x11x13** [comment]
Could you check your scdl.cfg file (should be at location `C:\Users\<username>\.config\scdl\scdl.cfg`) and make sure it has `client_id = a3e059563d7fd3372b49b37f00a00bcf` as one of the lines, it should automatically add it if it isn't there so I'm not sure why it gave that error...

**Comment by shejan0** [comment]
Ok I added that but now I am getting

```
E:\MoxiFloxi\SoundCloud>scdl -l https://soundcloud.com/moxifloxi -t -c --download-archive DOWNLOADED.txt 
Soundcloud Downloader
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\scdl-script.py", line 11, in <module>     
    load_entry_point('scdl==2.2.1', 'console_scripts', 'scdl')()
  File "C:\Program Files\Python38\lib\site-packages\scdl\scdl.py", line 196, in main
    arguments["--name-format"] = config["scdl"]["name_format"]
  File "C:\Program Files\Python38\lib\configparser.py", line 1254, in __getitem__   
    raise KeyError(key)
KeyError: 'name_format'
```

**Comment by 7x11x13** [comment]
Ohh I see the problem. setup.py wasn't configured to include the scdl.cfg file. I pushed a new update, try upgrading again

**Comment by shejan0** [comment]
Alright that seems to fix it.
