### ISSUE TITLE
Python giving scdl errors when trying to download music

### ISSUE THREAD

**Issue by noponydeepweb** [flyingrub/scdl#408]
I was trying to download a song but i get so many errors (installed via git clone and pip)
```
PS C:\Users\home\Desktop> scdl -l https://soundcloud.com/deltaxp/inferno --onlymp3 -f
Traceback (most recent call last):
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\Scripts\scdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scdl==2.6.1', 'console_scripts', 'scdl')())
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\lib\site-packages\scdl-2.6.1-py3.9.egg\scdl\scdl.py", line
144, in main
    config = get_config(config_file)
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\lib\site-packages\scdl-2.6.1-py3.9.egg\scdl\scdl.py", line
279, in get_config
    config.read_file(open(config_file, encoding="UTF-8"))
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 718, in read_file
    self._read(f, source)
  File "C:\Users\home\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 1085, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\home\\.config\\scdl\\scdl.cfg', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by 7x11x13** [comment]
Looks like the config file got corrupted somehow, try deleting C:\Users\home\.config\scdl\scdl.cfg and trying again

**Comment by noponydeepweb** [comment]
it worked! thanks man
