### ISSUE TITLE
I'm not sure what's the issue but I was not able to download

### ISSUE THREAD

**Issue by sidmehraajm** [flyingrub/scdl#418]
Downloading Pavan Nitai Chandra - Rama Navami Abhishek Kirtan - 10.4.22
Traceback (most recent call last):
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\Scripts\scdl.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\site-packages\scdl\scdl.py", line 239, in main
    download_url(client, **python_args)
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\site-packages\scdl\scdl.py", line 354, in download_url
    download_playlist(client, item.playlist, **kwargs)
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\site-packages\scdl\scdl.py", line 491, in download_playlist
    download_track(client, track, playlist_info, kwargs.get("strict_playlist"), **kwargs)
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\site-packages\scdl\scdl.py", line 715, in download_track
    filename, is_already_downloaded = download_hls(client, track, title, playlist_info, **kwargs)
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\site-packages\scdl\scdl.py", line 673, in download_hls
    p = subprocess.Popen(
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\sidda\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by hunkyburrito** [comment]
Make sure you have ffmpeg installed and in your system path.

**Comment by 89z** [comment]
please provide example URL

**Comment by sidmehraajm** [comment]
https://soundcloud.com/forest-fire-kirtans 
this was the profile, I was trying to download

**Comment by 89z** [comment]
If you try that one track, does it work?

**Comment by sidmehraajm** [comment]
I reinstalled everything just now, worked must have been an issue with my python version or ffmpeg
Thanks a lot
