### ISSUE TITLE
Keep getting this error "Error trying to set tags..."

### ISSUE THREAD

**Issue by CWTZL** [flyingrub/scdl#428]
Hey there a bit new to using this, but i'm trying to rip this mix in 256 acc. I've followed all the instructions as well as adding in my AuthID to the config file and I seem to be getting this error every time I attempt to download anything. Any help appreciated!

Camerons-MacBook-Pro-2:~ Cameron$ scdl -l https://soundcloud.com/hardfest/hsmf-2022-official-mixtape-series-montell2099-edm-identity-premiere
Soundcloud Downloader
Found a track
Downloading HSMF 2022 Official Mixtape Series: Montell2099 (EDM Identity Premiere)
Setting tags...
Error trying to set the tags...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scdl/scdl.py", line 741, in download_track
    set_metadata(track, filename, playlist_info, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scdl/scdl.py", line 892, in set_metadata
    elif mutagen_file.__class__ == mutagen.mp3.MP3 or mutagen_file.__class__ == mutagen.wave.WAVE:
AttributeError: module 'mutagen' has no attribute 'wave'
Error trying to set the tags...

**Comment by 7x11x13** [comment]
Try `pip install mutagen --upgrade`
