### ISSUE TITLE
Failing while downloading

### ISSUE THREAD

**Issue by washieiko** [flyingrub/scdl#452]
Can anyone help with this:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ibra\AppData\Local\Programs\Python\Python311\Scripts\scdl.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\ibra\AppData\Local\Programs\Python\Python311\Lib\site-packages\scdl\scdl.py", line 239, in main
    download_url(client, **python_args)
  File "C:\Users\ibra\AppData\Local\Programs\Python\Python311\Lib\site-packages\scdl\scdl.py", line 324, in download_url
    download_track(client, like.track, exit_on_fail=kwargs.get("strict_playlist"), **kwargs)
  File "C:\Users\ibra\AppData\Local\Programs\Python\Python311\Lib\site-packages\scdl\scdl.py", line 717, in download_track
    filename, is_already_downloaded = download_hls(client, track, title, playlist_info, **kwargs)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ibra\AppData\Local\Programs\Python\Python311\Lib\site-packages\scdl\scdl.py", line 673, in download_hls
    url = get_transcoding_m3u8(client, transcoding, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ibra\AppData\Local\Programs\Python\Python311\Lib\site-packages\scdl\scdl.py", line 636, in get_transcoding_m3u8
    return r.json()["url"]
           ~~~~~~~~^^^^^^^
KeyError: 'url'


ty for your time and help!

**Comment by max-ishere** [comment]
Can you please provide the URL for the track for troubleshooting?

**Comment by max-ishere** [comment]
Also based on the line numbers it seems that you are not using the latest version so if and when this is fixed you would probably have to update.
