### ISSUE TITLE
SCDL Has completely stopped working.

### ISSUE THREAD

**Issue by s3raph7** [flyingrub/scdl#466]
Hello, seems like the script isn't working anymore, after checking with different devices and different people, the script isn't working properly anymore. After running the command to download a song, the same error appears:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\<User>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\scdl.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\<User>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scdl\scdl.py", line 158, in main
    if not client.is_client_id_valid():
  File "C:\Users\<User>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\soundcloud\soundcloud.py", line 125, in is_client_id_valid
    next(
StopIteration

I have no idea what's going on, an answer would go a long way, thank you.

**Comment by ALegitCookie** [comment]
yeah i'm having similar problems on mac (Ventura) when trying to download a song or playlist:

warnings.warn(
Soundcloud Downloader
Traceback (most recent call last):
  File "/Users/tennison/Library/Python/3.9/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/Users/tennison/Library/Python/3.9/lib/python/site-packages/scdl/scdl.py", line 158, in main
    if not client.is_client_id_valid():
  File "/Users/tennison/Library/Python/3.9/lib/python/site-packages/soundcloud/soundcloud.py", line 125, in is_client_id_valid
    next(
StopIteration

**Comment by adithayyil** [comment]
Same, but I also seem to be getting a `MissingValueError` as you can see at the end when it tries to get the track.

```
Soundcloud Downloader
Traceback (most recent call last):
  File "/Users/silicon/Library/Python/3.9/lib/python/site-packages/dacite/core.py", line 72, in from_dict
    value = get_default_value_for_field(field, field_type)
  File "/Users/silicon/Library/Python/3.9/lib/python/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/silicon/Library/Python/3.9/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/Users/silicon/Library/Python/3.9/lib/python/site-packages/scdl/scdl.py", line 158, in main
    if not client.is_client_id_valid():
  File "/Users/silicon/Library/Python/3.9/lib/python/site-packages/soundcloud/soundcloud.py", line 125, in is_client_id_valid
    self.requests["track"](track_id=1032303631, use_auth=False)
  File "/Users/silicon/Library/Python/3.9/lib/python/site-packages/soundcloud/soundcloud.py", line 449, in __call__
    return self.convert_dict(r.json())
  File "/Users/silicon/Library/Python/3.9/lib/python/site-packages/soundcloud/soundcloud.py", line 429, in convert_dict
    return self.return_type.from_dict(d)
  File "/Users/silicon/Library/Python/3.9/lib/python/site-packages/soundcloud/resource/base.py", line 19, in from_dict
    return from_dict(cls, d, cls.dacite_config)
  File "/Users/silicon/Library/Python/3.9/lib/python/site-packages/dacite/core.py", line 76, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "track_format"
```

**Comment by s3raph7** [comment]
> Update:
> 
> I removed `track_format` in the [API wrapper](https://github.com/7x11x13/soundcloud.py/blob/main/soundcloud/resource/track.py#L48) and its seems to download fine now. But I am not sure what `track_format` does so not sure what that will break lol.

After a little bit of tweaking thanks to you advice, it works fine once again.

**Comment by 7x11x13** [comment]
Fixed in v2.7.5
