### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by surfacescan** [flyingrub/scdl#47]
Hi there - I recently was running scdl using this command:

scdl -l https://soundcloud.com/redbullmusicacademy/branko-eventually-feat-alex-rita-bison

And got this error - any ideas?

I am running version 1.1.0

Found a track
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.1.0', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 113, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 177, in parse_url
    download_track(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 351, in download_track
    stream_url = client.get(track.stream_url, allow_redirects=False)
  File "/usr/local/lib/python3.4/dist-packages/soundcloud/client.py", line 130, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python3.4/dist-packages/soundcloud/request.py", line 135, in make_request
    result.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized

**Comment by flyingrub** [comment]
seems like the track is not streamable. But i didn't tested anything for now.

**Comment by surfacescan** [comment]
I didn't know there are SoundCloud tracks that aren't streamable!?  Strange

**Comment by flyingrub** [comment]
https://developers.soundcloud.com/docs/api/reference#tracks
there is a boolean, if the track is streamabe streamable via API

**Comment by flyingrub** [comment]
can you retry cause here it works well : 
```
fly@Minotoor ~/workspace/scdl $ scdl -l https://soundcloud.com/redbullmusicacademy/branko-eventually-feat-alex-rita-bison
Soundcloud Downloader

Found a track
Downloading Branko - Eventually (feat. Alex Rita & Bison)
100% [......................................................] 3718999 / 3718999
Settings tags...

Branko - Eventually (feat. Alex Rita & Bison).mp3 Downloaded.
```
