### ISSUE TITLE
I believe that soundcloud changed some endpoints

### ISSUE THREAD

**Issue by lylecheatham** [flyingrub/scdl#471]
I tried to download a playlist ([all bangers by the way](https://soundcloud.com/lylecheatham/sets/apr-6-24)) and first got a StopIteration in `is_client_id_valid`. I poked into the code and found that this is because `soundcloud.com/tag_recent_tracks/{tag}` no longer returns any songs. I bypassed this and then got another error, so I think there may have been an overhaul of the api or something.

trace of the first error: 

```
/Users/lyle/Music/4.6.24>scdl -l https://soundcloud.com/lylecheatham/sets/apr-6-24
Soundcloud Downloader
Traceback (most recent call last):
  File "/Users/lyle/.pyenv/versions/music/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/Users/lyle/.pyenv/versions/3.8.5/envs/music/lib/python3.8/site-packages/scdl/scdl.py", line 158, in main
    if not client.is_client_id_valid():
  File "/Users/lyle/.pyenv/versions/3.8.5/envs/music/lib/python3.8/site-packages/soundcloud/soundcloud.py", line 125, in is_client_id_valid
    next(
StopIteration
```

```
/Users/lyle/Music/4.6.24>scdl --version
v2.7.3
```

**Comment by lylecheatham** [comment]
My bad, I was on an old version. Closing!
