### ISSUE TITLE
"path not found" error

### ISSUE THREAD

**Issue by JBWHH** [flyingrub/scdl#479]
Getting this error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\joelb\AppData\Local\Programs\Python\Python311\Scripts\scdl.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\joelb\AppData\Local\Programs\Python\Python311\Lib\site-packages\scdl\scdl.py", line 239, in main
    download_url(client, **python_args)
  File "C:\Users\joelb\AppData\Local\Programs\Python\Python311\Lib\site-packages\scdl\scdl.py", line 314, in download_url
    download_playlist(client, item, playlist_offset=offset, **kwargs)
  File "C:\Users\joelb\AppData\Local\Programs\Python\Python311\Lib\site-packages\scdl\scdl.py", line 463, in download_playlist
    os.makedirs(playlist_name)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

**Comment by 7x11x13** [comment]
What playlist are you trying to download, can you link it?

**Comment by JBWHH** [comment]
https://soundcloud.com/user-743719041/sets/rkogbeltilyi

it worked fine with the other playlists, not sure what i'm doing wrong here. Appreciate the reply!

**Comment by adithayyil** [comment]
The issue appears to be that `sanitize_filename` returns an empty string when given a string such as `'...'`

**Comment by 7x11x13** [comment]
Should be fixed in v2.7.8
