### ISSUE TITLE
Original File downloads broken

### ISSUE THREAD

**Issue by HeartbeatingForCenturies** [flyingrub/scdl#483]
https://soundcloud.com/egoseed/wrongthoughts

```
Traceback (most recent call last):
  File "c:\python311\scripts\scdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scdl==2.7.4', 'console_scripts', 'scdl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\scdl-2.7.4-py3.11.egg\scdl\scdl.py", line 239, in main
    download_url(client, **python_args)
  File "C:\Python311\Lib\site-packages\scdl-2.7.4-py3.11.egg\scdl\scdl.py", line 344, in download_url
    download_track(client, track, exit_on_fail=kwargs.get("strict_playlist"), **kwargs)
  File "C:\Python311\Lib\site-packages\scdl-2.7.4-py3.11.egg\scdl\scdl.py", line 712, in download_track
    filename, is_already_downloaded = download_original_file(client, track, title, playlist_info, **kwargs)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\scdl-2.7.4-py3.11.egg\scdl\scdl.py", line 535, in download_original_file
    url = client.get_track_original_download(track.id, track.secret_token)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\soundcloud\soundcloud.py", line 280, in get_track_original_download
    download = self.requests["track_original_download"](track_id=track_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\soundcloud\soundcloud.py", line 448, in __call__
    r.raise_for_status()
  File "C:\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-v2.soundcloud.com/tracks/535045215/download?client_id=a3e059563d7fd3372b49b37f00a00bcf
```

**Comment by adithayyil** [comment]
Pretty sure you need to add a valid `auth_token` to your config file

**Comment by 7x11x13** [comment]
> Pretty sure you need to add a valid `auth_token` to your config file

It seems this is the case now. We shouldn't try to download the original file if the auth token is not valid

**Comment by 7x11x13** [comment]
Changed in v2.7.10 so it won't try to download the original file if the auth token is invalid. If you want to download the original file make sure your auth token is valid
