### ISSUE TITLE
Windows rename exception from specific characters

### ISSUE THREAD

**Issue by tripflex** [flyingrub/scdl#49]
Looks like on Windows it throws an exception if the filename has certain characters in it.  Specifically I get the error for a file with a question mark `?` in it:

```python
  File "c:\Python34\lib\shutil.py", line 522, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\myles\\Music\\SC\\download.8jmfxs16.tmp' -> 'MAYHEM_x_ANTISERUM_vs_GENT_x_JAWNS_-_WHERE_YOU_BEEN?.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\scdl-script.py", line 9, in <module>
    load_entry_point('scdl==v1.1.1', 'console_scripts', 'scdl')()
  File "c:\Python34\lib\site-packages\scdl\scdl.py", line 118, in main
    download_user_favorites(who_am_i())
  File "c:\Python34\lib\site-packages\scdl\scdl.py", line 290, in download_user_favorites
    download_track(track)
  File "c:\Python34\lib\site-packages\scdl\scdl.py", line 378, in download_track
    wget.download(url, filename)
  File "c:\Python34\lib\site-packages\wget.py", line 320, in download
    shutil.move(tmpfile, filename)
  File "c:\Python34\lib\shutil.py", line 534, in move
    copy2(src, real_dst)
  File "c:\Python34\lib\shutil.py", line 244, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\Python34\lib\shutil.py", line 108, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'MAYHEM_x_ANTISERUM_vs_GENT_x_JAWNS_-_WHERE_YOU_BEEN?.mp3'
```

**Comment by e2del** [comment]
#145
