### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by philippeboyd** [flyingrub/scdl#5]
I used the install command but the programm won't install. Invalid syntax?

```
pip3 install scdl
// also tried
sudo pip3 install scdl
```

```
Downloading/unpacking scdl
  Downloading scdl-0.9.tar.gz
  Running setup.py (path:/tmp/pip_build_root/scdl/setup.py) egg_info for package scdl

Downloading/unpacking docopt (from scdl)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/docopt/setup.py) egg_info for package docopt

Downloading/unpacking soundcloud (from scdl)
  Downloading soundcloud-0.4.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/soundcloud/setup.py) egg_info for package soundcloud

Downloading/unpacking wget (from scdl)
  Downloading wget-2.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/wget/setup.py) egg_info for package wget

Downloading/unpacking configparser (from scdl)
  Downloading configparser-3.3.0r2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/configparser/setup.py) egg_info for package configparser
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/usr/lib/python3.4/distutils/core.py", line 18, in <module>
        from distutils.config import PyPIRCCommand
      File "/usr/lib/python3.4/distutils/config.py", line 7, in <module>
        from configparser import ConfigParser
      File "/tmp/pip_build_root/configparser/configparser.py", line 397
        _KEYCRE = re.compile(ur"%\(([^)]+)\)s")
                                             ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 5, in <module>

    import distutils.core

  File "/usr/lib/python3.4/distutils/core.py", line 18, in <module>

    from distutils.config import PyPIRCCommand

  File "/usr/lib/python3.4/distutils/config.py", line 7, in <module>

    from configparser import ConfigParser

  File "/tmp/pip_build_root/configparser/configparser.py", line 397

    _KEYCRE = re.compile(ur"%\(([^)]+)\)s")

                                         ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/configparser
Storing debug log for failure in /home/philippe/.pip/pip.log
```

**Comment by travs** [comment]
@staringispolite 's instructions worked for me!

**Comment by Montana** [comment]
This seems to be the fix, had to actually go into `/bin` and `-rm -rf` the `scdl` package because pip3/pip wasn't doing it. Just FYI. Thanks so much man.
