### ISSUE TITLE
401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by uahim** [flyingrub/scdl#50]
`requests.exceptions.HTTPError: 401 Client Error: Unauthorized`
as of today, this is what I'm getting for sets/tracks, win32, scdl v1.1.1

is this just me, or did they change something on their servers?

**Comment by Spotlight0xff** [comment]
All Tracks/Sets? Can you provide an example please, so we can try to
reproduce the problem?

**Comment by uahim** [comment]
https://soundcloud.com/ukgoldfilm/sets/uk-gold-soundtrack
on a second look, it seems to be all tracks from this set only, my bad

**Comment by flyingrub** [comment]
```
fly@Minotoor ~/Musique/test $ scdl -l https://soundcloud.com/ukgoldfilm/sets/uk-gold-soundtrack
Soundcloud Downloader

Found a playlist
Track n°1
Downloading Tap24+ Hiha24 (Yorke / Greenwood)
100% [......................................................] 3093314 / 3093314
Settings tags...

Tap24+ Hiha24 (Yorke  Greenwood).mp3 Downloaded.

Track n°2
Downloading Mosquito Beat Slow (Yorke)
100% [......................................................] 1161089 / 1161089
Settings tags...

Mosquito Beat Slow (Yorke).mp3 Downloaded.

```
it works fine here

**Comment by Spotlight0xff** [comment]
Works here too, Linux though. Does the firewall interfere? Does other songs work?

**Comment by uahim** [comment]
yes, other sets and tracks work fine, weird

**Comment by philippeboyd** [comment]
I got the same error today with a previous version.

```shell
scdl -l https://soundcloud.com/louis-vivet-music/downbeat-feat-gavrielle-1

Found a track
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.0.7', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 87, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 151, in parse_url
    download_track(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 315, in download_track
    stream_url = client.get(track.stream_url, allow_redirects=False)
  File "/usr/local/lib/python3.4/dist-packages/soundcloud/client.py", line 130, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python3.4/dist-packages/soundcloud/request.py", line 135, in make_request
    result.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized
```

I then upgraded to 1.1.1 using 

```shell
sudo pip3 install scdl --upgrade
```

And everything went fine.

**Comment by flyingrub** [comment]
issue fixed when upgrading
