### ISSUE TITLE
404 on same song

### ISSUE THREAD

**Issue by CodeNameTheOnlyOne** [flyingrub/scdl#51]
does it every time for me on certain songs like for ex https://soundcloud.com/alisonwonderland/iwantyou-ganzflip-cdm

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.1.1', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 113, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 184, in parse_url
    download_user_favorites(item)
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 290, in download_user_favorites
    download_track(track)
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 351, in download_track
    stream_url = client.get(track.stream_url, allow_redirects=False)
  File "/usr/local/lib/python3.4/site-packages/soundcloud/client.py", line 130, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python3.4/site-packages/soundcloud/request.py", line 135, in make_request
    result.raise_for_status()
  File "/usr/local/lib/python3.4/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

**Comment by CodeNameTheOnlyOne** [comment]
Just going to leave this here
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 256, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.1.1', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 113, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 184, in parse_url
    download_user_favorites(item)
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 290, in download_user_favorites
    download_track(track)
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 351, in download_track
    stream_url = client.get(track.stream_url, allow_redirects=False)
  File "/usr/local/lib/python3.4/site-packages/soundcloud/client.py", line 130, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python3.4/site-packages/soundcloud/request.py", line 123, in make_request
    result = request_func('%s?%s' % (url, qs), **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:600)

**Comment by Spotlight0xff** [comment]
Hello! This issue has been known for quite some time, but as far as I know,
there is no fix :/ But there is a PR which adds a exception handling for
URLs returning 404. (I'm on mobile, so I can't reference)
Also flyingrub is currently working on another project and doesn't work
actively on scdl anymore.

**Comment by CodeNameTheOnlyOne** [comment]
Ok Thanks

**Comment by syphoxy** [comment]
is there not a solution for this?

**Comment by Spotlight0xff** [comment]
Well... I'm not sure.
I found a way, but I don't know how usable it is:
**Using a different client_id**

`http://api.soundcloud.com/i1/tracks/158191215/streams?client_id=$client_id`

https://gist.github.com/Spotlight0xff/2233c52d59fa345da6ec#file-restricted

This is the data by using the scdl-client_id (9dbef61eb005cb526480279a0cc868c4), it shows 3 entries.

Now using a different client_id (used my client_id, which was generated when I logged into soundcloud)
https://gist.github.com/Spotlight0xff/2233c52d59fa345da6ec#file-unrestricted

As you can see, now are 4 entries visible and you can download the file using http_mp3_128_url!

Btw, maybe another link can be used (maybe the RTMP one?) to download the file, don't know.

So, there is a solution, but you'd have to provide a client_id.

Cheers!

**Comment by flyingrub** [comment]
interesting !
how did you get the other url ?

**Comment by Spotlight0xff** [comment]
mobile page:
https://w.soundcloud.com/player/?visual=true&url=https%3A//api.soundcloud.com/tracks/158191215

using firebug (when you hover over the play-button you can see a new request :)

**Comment by flyingrub** [comment]
yes but for th registred and unregistred link ?

**Comment by Spotlight0xff** [comment]
what do you mean?
https://gist.github.com/Spotlight0xff/2233c52d59fa345da6ec#file-restricted ?
and the unrestricted one aswell with the method mentioned above.
One is with my own client_id and the other one (restricted) with the scdl-client_id.

**Comment by flyingrub** [comment]
what i mean is that it's not in the track_info ...
and the stream url redirect to only of those.

**Comment by Spotlight0xff** [comment]
Yes, it's not in the track_info, i construct the URL by myself (using the track-id):

```
def alternative_download(track, title):
    track_id = str(track.id)
    url = 'http://api.soundcloud.com/i1/tracks/' + track_id + '/streams?client_id=a3e059563d7fd3372b49b37f00a00bcf'
    res = urllib.request.urlopen(url)
    data = res.read().decode()
    js = json.loads(data)
    try:
        mp3_url = js['http_mp3_128_url']
    except KeyError:
        log('http_mp3_128_url not found in json response, report to developer.',    strverbosity=0)
        return
    filename = construct_filename(track, title)
    log("Downloading " + title, strverbosity=1)
    download_file(track, mp3_url, filename)
```

**Comment by flyingrub** [comment]
issue is still present : reopening

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/d7925538e11570f2a71637539f0905c251ded9ad
