### ISSUE TITLE
Songtitles with "~" make scdl crash

### ISSUE THREAD

**Issue by nltommynl** [flyingrub/scdl#52]
OS: OSX 10.9

Song:
https://soundcloud.com/octobersveryown/drake-6-god?in=tommydehaas/sets/its-always-summer-in-miami

Title: Drake ~ 6 God (Prod. by Boi-1da & Syk Sense)

Result:
Track n°27
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.1.1', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 113, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 180, in parse_url
    download_playlist(item)
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 324, in download_playlist
    download_track(mp3_url, playlist.title)
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 351, in download_track
    stream_url = client.get(track.stream_url, allow_redirects=False)
  File "/usr/local/lib/python3.4/site-packages/soundcloud/client.py", line 130, in _request
    return wrapped_resource(make_request(method, url, kwargs))
  File "/usr/local/lib/python3.4/site-packages/soundcloud/request.py", line 135, in make_request
    result.raise_for_status()
  File "/usr/local/lib/python3.4/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

**Comment by nltommynl** [comment]
Also on:

https://soundcloud.com/theweeknd/mike-will-made-it-drinks-on-us-feat-the-weeknd-swae-lee-future?in=tommydehaas/sets/its-always-summer-in-miami

Title: Mike Will Made - It - Drinks On Us Feat. The Weeknd, Swae Lee & Future

**Comment by Spotlight0xff** [comment]
I don't think scdl crashes because of the tilde. Some songs are not downloadable (I think because it uses RTMPT to stream songs), but I'm trying to find a solution to this, as it happens to a lot songs!
Cheers.

**Comment by flyingrub** [comment]
when i go on the webpage with my fresh linux install it says : "You need Adobe Flash to play this track.
Please install Flash and reload the page."
there will be some reverse to do ...

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/d7925538e11570f2a71637539f0905c251ded9ad

**Comment by flyingrub** [comment]
use your own auth token resolve the error too...
it's explained how to add it in the readme.
