### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ghost** [flyingrub/scdl#6]
All works fine in installing it with pip3 install scdl (also tried with sudo) until

```
...
Downloading/unpacking configparser (from scdl)
  Downloading configparser-3.3.0r2.tar.gz
  Running setup.py (path:/tmp/pip_build_felix/configparser/setup.py) egg_info for package configparser
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/usr/lib/python3.4/distutils/core.py", line 18, in <module>
        from distutils.config import PyPIRCCommand
      File "/usr/lib/python3.4/distutils/config.py", line 7, in <module>
        from configparser import ConfigParser
      File "/tmp/pip_build_felix/configparser/configparser.py", line 397
        _KEYCRE = re.compile(ur"%\(([^)]+)\)s")
                                             ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 5, in <module>

    import distutils.core

  File "/usr/lib/python3.4/distutils/core.py", line 18, in <module>

    from distutils.config import PyPIRCCommand

  File "/usr/lib/python3.4/distutils/config.py", line 7, in <module>

    from configparser import ConfigParser

  File "/tmp/pip_build_felix/configparser/configparser.py", line 397

    _KEYCRE = re.compile(ur"%\(([^)]+)\)s")

                                         ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_felix/configparser
Storing debug log for failure in /home/felix/.pip/pip.log
```

**Comment by flyingrub** [comment]
configparser is built in with python3 no need to install it. (fixed issue)
