### ISSUE TITLE
SSL Issues

### ISSUE THREAD

**Issue by zethussuen** [flyingrub/scdl#67]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/http/client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.3.2', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 118, in main
    download_all_user_tracks(who_am_i())
  File "/usr/local/lib/python3.4/site-packages/scdl/scdl.py", line 224, in download_all_user_tracks
    response = urllib.request.urlopen(url)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
```

**Comment by iraritchiemeek** [comment]
Same issue

**Comment by flyingrub** [comment]
it seems the soundcloud api has a untrusted certificate... ? (will work on it later)

**Comment by maexlich** [comment]
Simple but ugly fix:
add these two lines after the import statements of scdl.py:

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

Should find a way to allow individual certificates... 
Seems to be an error upstream in wget.py which is missing this functionality

**Comment by flyingrub** [comment]
i just tested here it worked, please update your system and retry.

**Comment by maexlich** [comment]
Might be a OS X only problem
(/usr/local/Cellar ist the path for python stuff installed in OS X)
maybe Apple does not trust some certificate that is normally trusted on linux distributions...

**Comment by iraritchiemeek** [comment]
Still broken, i'm on OSX. 
Added the two lines @maexlich recommended and that fixed it for me.

**Comment by nickw444** [comment]
Can confirm this being an issue on OSX as well. However, I /don't really/ want to "fix" this by trusting an unverified certificate.

**Comment by flyingrub** [comment]
exact, it's not a fix.

**Comment by flyingrub** [comment]
any update on this issue on os x ?
@nickw444 @iraritchiemeek @zethussuen

**Comment by nickw444** [comment]
No clue, haven't actually looked at this, nor used SCDL since I came across this (Haven't needed to download from SC).

**Comment by flyingrub** [comment]
if you could try with the latest scdl version on gtihub, it would be great :)

**Comment by nickw444** [comment]
Working perfectly!

**Comment by flyingrub** [comment]
nice ! we can close this. An update will be pushed to pypi in the next days.
