### ISSUE TITLE
No module named configparser

### ISSUE THREAD

**Issue by iraritchiemeek** [flyingrub/scdl#68]
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.3.2', 'console_scripts', 'scdl')()
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 455, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 2531, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 2241, in load
  File "/usr/local/lib/python2.7/site-packages/scdl/scdl.py", line 34, in <module>
    import configparser
ImportError: No module named configparser

**Comment by flyingrub** [comment]
You need to install configparser by hand, or you can simply install pip and run `pip install scdl`
it's python 3 btw.
