### ISSUE TITLE
Error handling filename.

### ISSUE THREAD

**Issue by N07070** [flyingrub/scdl#73]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/shutil.py", line 522, in move
    os.rename(src, real_dst)
OSError: [Errno 22] Invalid argument: '/media/n07070/USBATTERY/LaDétenteGénérale/download.j9v18ksy.tmp' -> 'Sacha Mambo DJ Set @ Maison Jager:Vice (2014_09_18).mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.3.2', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 115, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 190, in parse_url
    download_all_user_tracks(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 235, in download_all_user_tracks
    parse_url(this_url)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 179, in parse_url
    download_track(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 398, in download_track
    wget.download(url, filename)
  File "/usr/local/lib/python3.4/dist-packages/wget.py", line 320, in download
    shutil.move(tmpfile, filename)
  File "/usr/lib/python3.4/shutil.py", line 534, in move
    copy2(src, real_dst)
  File "/usr/lib/python3.4/shutil.py", line 244, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.4/shutil.py", line 108, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'Sacha Mambo DJ Set @ Maison Jager:Vice (2014_09_18).mp3'

```

**Comment by Spotlight0xff** [comment]
Works fine for me, can you provide some more information?
Like OS/Version, Filesystem?
Is your wget up2date? (shouldn't be an issue but just to be sure)

Cheers

**Comment by flyingrub** [comment]
working fine here too.

**Comment by N07070** [comment]
Linux, eOS, all up to date.

**Comment by Spotlight0xff** [comment]
What filesystem are you using on /media?
Can you try to change your savepath and see if it works somewhere else?

**Comment by N07070** [comment]
FAT32. I cannot before August.

**Comment by flyingrub** [comment]
any news @N07070 ?

**Comment by N07070** [comment]
Yup, can't reproduce.
