### ISSUE TITLE
URLError

### ISSUE THREAD

**Issue by abstracted** [flyingrub/scdl#75]
After running "scld -l https://soundcloud.com/physicslab/ -a" I received the following error. 

- - - - - - - - - - - - - - - - - - - 

Traceback (most recent call last):
  File "/usr/local/lib/python3.3/urllib/request.py", line 1248, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python3.3/http/client.py", line 1061, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.3/http/client.py", line 1099, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.3/http/client.py", line 1057, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.3/http/client.py", line 902, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.3/http/client.py", line 840, in send
    self.connect()
  File "/usr/local/lib/python3.3/http/client.py", line 1194, in connect
    self.timeout, self.source_address)
  File "/usr/local/lib/python3.3/socket.py", line 417, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.3.2', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.3/site-packages/scdl/scdl.py", line 115, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.3/site-packages/scdl/scdl.py", line 190, in parse_url
    download_all_user_tracks(item)
  File "/usr/local/lib/python3.3/site-packages/scdl/scdl.py", line 224, in download_all_user_tracks
    response = urllib.request.urlopen(url)
  File "/usr/local/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.3/urllib/request.py", line 469, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.3/urllib/request.py", line 487, in _open
    '_open', req)
  File "/usr/local/lib/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.3/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.3/urllib/request.py", line 1251, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

- - - - - - - - - - - - - 

Linux - CentOS 6.6
Python - 3.3
SCDL - v1.3.2

**Comment by flyingrub** [comment]
soundcloud is changing their api...

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/3f7fc89f1fcb27f020399eab996b03c0ae005ab9
fixed here. but this version also include a new download type so be carefull using this one.

**Comment by flyingrub** [comment]
fixed & i'm going to push a new release

**Comment by abstracted** [comment]
I don't believe the version I have corresponds to the fixes. the scdl.py file I have appears to be different. After reinstalling with pip3 i get the same exact version. I suppose I'll wait for the new release.

**Comment by flyingrub** [comment]
yup, i've found a possible bug in the soundcloud api. I'm waiting for their answer to push.
