### ISSUE TITLE
Error trying to set the tags...: 'module' object has no attribute 'urlretrieve'

### ISSUE THREAD

**Issue by sedrubal** [flyingrub/scdl#84]
Everything is working fine but on every song download scdl is saying:

```
Error trying to set the tags...
```

I found out that the underlying python error is:

```
'module' object has no attribute 'urlretrieve'
```

I'm running `fedora 22` with `urllib3 (1.11)` and `scdl (1.3.2)` (both installed through `pip`).

**Comment by flyingrub** [comment]
can you provide the full log ?

2015-09-01 22:51 GMT+02:00 sedrubal <notifications@github.com>:

**Comment by sedrubal** [comment]
Of course, sorry. I removed the `try - except` in [line 370](https://github.com/flyingrub/scdl/blob/master/scdl/scdl.py#L370):

```python
Settings tags...
Traceback (most recent call last):
  File "/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.3.2', 'console_scripts', 'scdl')()
  File "/usr/lib/python2.7/site-packages/scdl/scdl.py", line 116, in main
    parse_url(arguments["-l"])
  File "/usr/lib/python2.7/site-packages/scdl/scdl.py", line 180, in parse_url
    download_track(item)
  File "/usr/lib/python2.7/site-packages/scdl/scdl.py", line 404, in download_track
    settags(track, filename)
  File "/usr/lib/python2.7/site-packages/scdl/scdl.py", line 438, in settags
    requests.urlretrieve(artwork_url, '/tmp/scdl.jpg')
AttributeError: 'module' object has no attribute 'urlretrieve'

```

**Comment by Spotlight0xff** [comment]
scdl is supposed to be running on Python 3 - not 2.
Try `pip2 uninstall scdl` and then `pip3 install scdl`

**Comment by flyingrub** [comment]
That's what i thought :)

**Comment by sedrubal** [comment]
Oops you're right. I'm sorry, thank you ;)
