### ISSUE TITLE
Trouble installing library

### ISSUE THREAD

**Issue by amz4u2nv** [flyingrub/scdl#86]
Hi,
Can anyone help with installing the library - 
getting the following from the log - 
      File "mutagen/_util.py", line 468

        if c == u"\x00":

                      ^

    SyntaxError: invalid syntax

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/mutagen/setup.py", line 222, in <module>

    from mutagen import version_string

  File "mutagen/__init__.py", line 23, in <module>

    from mutagen._util import MutagenError

  File "mutagen/_util.py", line 468

    if c == u"\x00":

                  ^

SyntaxError: invalid syntax

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /home/pi/build/mutagen

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/pi/build/mutagen

Any idea what I am doing wrong?

Thanks

**Comment by flyingrub** [comment]
try to install mutagen alone with easy_install and pip

**Comment by amz4u2nv** [comment]
pi@raspberrypi ~ $ sudo easy_install3 mutagen
Searching for mutagen
Reading http://pypi.python.org/simple/mutagen/
Best match: mutagen 1.30
Downloading https://pypi.python.org/packages/source/m/mutagen/mutagen-1.30.tar.gz#md5=2c2069bd6a8245f99845f160da37f2ac
Processing mutagen-1.30.tar.gz
Running mutagen-1.30/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qtbc6z/mutagen-1.30/egg-dist-tmp-butmms
Traceback (most recent call last):
  File "/usr/bin/easy_install3", line 9, in <module>
    load_entry_point('distribute==0.6.24dev-r0', 'console_scripts', 'easy_install')()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1931, in main
    with_ei_usage(lambda:
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1912, in with_ei_usage
    return f()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1935, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python3.2/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.2/distutils/dist.py", line 917, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.2/distutils/dist.py", line 936, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 368, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 608, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 638, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 828, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1105, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1094, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 31, in run_setup
    lambda: exec(compile(open(
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 73, in run
    return func()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 34, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'})
  File "setup.py", line 222, in <module>
  File "/tmp/easy_install-qtbc6z/mutagen-1.30/mutagen/__init__.py", line 23, in <module>
  File "/tmp/easy_install-qtbc6z/mutagen-1.30/mutagen/_util.py", line 468
    if c == u"\x00":
                  ^
SyntaxError: invalid syntax

same for pip
Downloading/unpacking mutagen
  Running setup.py egg_info for package mutagen
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/mutagen/setup.py", line 222, in <module>
        from mutagen import version_string
      File "mutagen/__init__.py", line 23, in <module>
        from mutagen._util import MutagenError
      File "mutagen/_util.py", line 468
        if c == u"\x00":
                      ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/mutagen/setup.py", line 222, in <module>

    from mutagen import version_string

  File "mutagen/__init__.py", line 23, in <module>

    from mutagen._util import MutagenError

  File "mutagen/_util.py", line 468

    if c == u"\x00":

                  ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/mutagen
Storing complete log in /root/.pip/pip.log

**Comment by amz4u2nv** [comment]
mutagen only supports 3.3+.. will try to install 
install it now.. to see if that makes any difference..

**Comment by amz4u2nv** [comment]
Can't get it to work...
Anyone got step by step process to install this on raspberry pi.

**Comment by flyingrub** [comment]
i managed to run it on my rasp by compiling python3.4 on it (it takes a lot of time).
You can use screen or i recommend you to cross compile it.

**Comment by amz4u2nv** [comment]
Ok I've managed to install it on synology box.. just one more question..
Not sure where the file is located doing - 
scdl doesn't do anything
-ash: scdl: not found
do you where the path to the file would be?

**Comment by amz4u2nv** [comment]
never mind found it.
Thanks
