### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc2' 

### ISSUE THREAD

**Issue by robbieh** [flyingrub/scdl#89]
Seems pretty self-explanatory. The "no" for "number" uses a non-ascii symbol in several places.

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.3.2', 'console_scripts', 'scdl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/scdl/scdl.py", line 234
SyntaxError: Non-ASCII character '\xc2' in file /usr/local/lib/python2.7/dist-packages/scdl/scdl.py on line 234, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by flyingrub** [comment]
This soft require python3.
