### ISSUE TITLE
No module named 'six' (user issue?)

### ISSUE THREAD

**Issue by moredillon** [flyingrub/scdl#93]
I uninstalled and reinstalled the six module every way. Keep getting that error. What am I missing here? Thanks.

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 7, in <module>
    from scdl.scdl import main
  File "/usr/local/lib/python3.5/site-packages/scdl/scdl.py", line 43, in <module>
    import soundcloud
  File "/usr/local/lib/python3.5/site-packages/soundcloud/__init__.py", line 8, in <module>
    from soundcloud.client import Client
  File "/usr/local/lib/python3.5/site-packages/soundcloud/client.py", line 8, in <module>
    from soundcloud.request import make_request
  File "/usr/local/lib/python3.5/site-packages/soundcloud/request.py", line 7, in <module>
    import six
ImportError: No module named 'six'

**Comment by edsko** [comment]
I had the same problem, missing dependency? Anyway,

```
# pip3 install six
Collecting six
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.10.0
```

resolved it for me.

**Comment by flyingrub** [comment]
it's a missing dependency, but it come from the soundcloud library.
