### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0'

### ISSUE THREAD

**Issue by ayush--s** [flyingrub/scdl#94]
`scdl -l https://soundcloud.com/twiceasnice-1/sets/twice-as-nice-remixes `

```
Soundcloud Downloader

Found a playlist
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.3.2', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 115, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 182, in parse_url
    download_playlist(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 325, in download_playlist
    log('Track n\xb0%d' % (count), strverbosity=1)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 67, in log
    print(colored(str, 'white'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 12: ordinal not in range(128)
```

**Comment by flyingrub** [comment]
should be fixed too by the latest commit.

**Comment by flyingrub** [comment]
please test and report :)

**Comment by ayush--s** [comment]
fixed :+1:
