### ISSUE TITLE
Command -a not working

### ISSUE THREAD

**Issue by Markkop** [flyingrub/scdl#98]
Hey! I just started using linux (but I don't believe this is the problem) and couldn't use the -a argument when downloading all tracks and reposts from an user.

Here is what appears:
```
MarkPC mark # scdl -l https://soundcloud.com/kiasmos/ -a
Soundcloud Downloader

Found an user profile
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1223, in connect
    super().connect()
  File "/usr/lib/python3.4/http/client.py", line 834, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.3.2', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 115, in main
    parse_url(arguments["-l"])
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 190, in parse_url
    download_all_user_tracks(item)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 224, in download_all_user_tracks
    response = urllib.request.urlopen(url)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by flyingrub** [comment]
your version of scdl is out of date. 
same bug as here : https://github.com/flyingrub/scdl/issues/85

**Comment by Markkop** [comment]
Oh, thanks. Didn't find a way to update at the home page, but I did it after you linked #85.
However, it keeps trying to retrieve music, even though there are like four or five in the page I'm trying to retrieve. I tried some others profiles as well, getting the same.

```
MarkPC mark # scdl -l https://soundcloud.com/kiasmos -a
Soundcloud Downloader

Starting new HTTPS connection (1): api.soundcloud.com
Found an user profile
Retrieving all the track of user Kiasmos...
```

**Comment by flyingrub** [comment]
try with master (remove the old one before)
```
git clone https://github.com/flyingrub/scdl.git
cd scdl
python3 setup.py install
```

**Comment by Markkop** [comment]
Thanks, it's working! Awesome soft :D
